// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1.2 (64-bit)
// Version: 2022.1.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module apply_watermark_compute_watermark (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        inStream_dout,
        inStream_num_data_valid,
        inStream_fifo_cap,
        inStream_empty_n,
        inStream_read,
        xStream_dout,
        xStream_num_data_valid,
        xStream_fifo_cap,
        xStream_empty_n,
        xStream_read,
        yStream_dout,
        yStream_num_data_valid,
        yStream_fifo_cap,
        yStream_empty_n,
        yStream_read,
        outStream_din,
        outStream_num_data_valid,
        outStream_fifo_cap,
        outStream_full_n,
        outStream_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [511:0] inStream_dout;
input  [1:0] inStream_num_data_valid;
input  [1:0] inStream_fifo_cap;
input   inStream_empty_n;
output   inStream_read;
input  [31:0] xStream_dout;
input  [1:0] xStream_num_data_valid;
input  [1:0] xStream_fifo_cap;
input   xStream_empty_n;
output   xStream_read;
input  [31:0] yStream_dout;
input  [1:0] yStream_num_data_valid;
input  [1:0] yStream_fifo_cap;
input   yStream_empty_n;
output   yStream_read;
output  [511:0] outStream_din;
input  [1:0] outStream_num_data_valid;
input  [1:0] outStream_fifo_cap;
input   outStream_full_n;
output   outStream_write;

reg ap_idle;
reg inStream_read;
reg xStream_read;
reg yStream_read;
reg outStream_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
reg    ap_block_state20_pp0_stage0_iter19;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln107_fu_468_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] watermark_address0;
reg    watermark_ce0;
wire   [16:0] watermark_q0;
wire   [7:0] watermark_address1;
reg    watermark_ce1;
wire   [16:0] watermark_q1;
wire   [7:0] watermark_address2;
reg    watermark_ce2;
wire   [16:0] watermark_q2;
wire   [7:0] watermark_address3;
reg    watermark_ce3;
wire   [16:0] watermark_q3;
wire   [7:0] watermark_address4;
reg    watermark_ce4;
wire   [16:0] watermark_q4;
wire   [7:0] watermark_address5;
reg    watermark_ce5;
wire   [16:0] watermark_q5;
wire   [7:0] watermark_address6;
reg    watermark_ce6;
wire   [16:0] watermark_q6;
wire   [7:0] watermark_address7;
reg    watermark_ce7;
wire   [16:0] watermark_q7;
wire   [7:0] watermark_address8;
reg    watermark_ce8;
wire   [16:0] watermark_q8;
wire   [7:0] watermark_address9;
reg    watermark_ce9;
wire   [16:0] watermark_q9;
wire   [7:0] watermark_address10;
reg    watermark_ce10;
wire   [16:0] watermark_q10;
wire   [7:0] watermark_address11;
reg    watermark_ce11;
wire   [16:0] watermark_q11;
wire   [7:0] watermark_address12;
reg    watermark_ce12;
wire   [16:0] watermark_q12;
wire   [7:0] watermark_address13;
reg    watermark_ce13;
wire   [16:0] watermark_q13;
wire   [7:0] watermark_address14;
reg    watermark_ce14;
wire   [16:0] watermark_q14;
wire   [7:0] watermark_address15;
reg    watermark_ce15;
wire   [16:0] watermark_q15;
reg    inStream_blk_n;
wire    ap_block_pp0_stage0;
reg    xStream_blk_n;
reg    yStream_blk_n;
reg    outStream_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [23:0] tmp_data_fu_485_p1;
reg   [23:0] tmp_data_reg_1549;
reg   [23:0] tmp_data_reg_1549_pp0_iter2_reg;
reg   [23:0] trunc_ln4_reg_1554;
reg   [23:0] trunc_ln4_reg_1554_pp0_iter2_reg;
reg   [23:0] trunc_ln4_reg_1554_pp0_iter3_reg;
reg   [23:0] trunc_ln_reg_1559;
reg   [23:0] trunc_ln_reg_1559_pp0_iter2_reg;
reg   [23:0] trunc_ln_reg_1559_pp0_iter3_reg;
reg   [23:0] trunc_ln_reg_1559_pp0_iter4_reg;
reg   [23:0] trunc_ln110_s_reg_1564;
reg   [23:0] trunc_ln110_s_reg_1564_pp0_iter2_reg;
reg   [23:0] trunc_ln110_s_reg_1564_pp0_iter3_reg;
reg   [23:0] trunc_ln110_s_reg_1564_pp0_iter4_reg;
reg   [23:0] trunc_ln110_s_reg_1564_pp0_iter5_reg;
reg   [23:0] trunc_ln110_1_reg_1569;
reg   [23:0] trunc_ln110_1_reg_1569_pp0_iter2_reg;
reg   [23:0] trunc_ln110_1_reg_1569_pp0_iter3_reg;
reg   [23:0] trunc_ln110_1_reg_1569_pp0_iter4_reg;
reg   [23:0] trunc_ln110_1_reg_1569_pp0_iter5_reg;
reg   [23:0] trunc_ln110_1_reg_1569_pp0_iter6_reg;
reg   [23:0] trunc_ln110_2_reg_1574;
reg   [23:0] trunc_ln110_2_reg_1574_pp0_iter2_reg;
reg   [23:0] trunc_ln110_2_reg_1574_pp0_iter3_reg;
reg   [23:0] trunc_ln110_2_reg_1574_pp0_iter4_reg;
reg   [23:0] trunc_ln110_2_reg_1574_pp0_iter5_reg;
reg   [23:0] trunc_ln110_2_reg_1574_pp0_iter6_reg;
reg   [23:0] trunc_ln110_2_reg_1574_pp0_iter7_reg;
reg   [23:0] trunc_ln110_3_reg_1579;
reg   [23:0] trunc_ln110_3_reg_1579_pp0_iter2_reg;
reg   [23:0] trunc_ln110_3_reg_1579_pp0_iter3_reg;
reg   [23:0] trunc_ln110_3_reg_1579_pp0_iter4_reg;
reg   [23:0] trunc_ln110_3_reg_1579_pp0_iter5_reg;
reg   [23:0] trunc_ln110_3_reg_1579_pp0_iter6_reg;
reg   [23:0] trunc_ln110_3_reg_1579_pp0_iter7_reg;
reg   [23:0] trunc_ln110_3_reg_1579_pp0_iter8_reg;
reg   [23:0] trunc_ln110_4_reg_1584;
reg   [23:0] trunc_ln110_4_reg_1584_pp0_iter2_reg;
reg   [23:0] trunc_ln110_4_reg_1584_pp0_iter3_reg;
reg   [23:0] trunc_ln110_4_reg_1584_pp0_iter4_reg;
reg   [23:0] trunc_ln110_4_reg_1584_pp0_iter5_reg;
reg   [23:0] trunc_ln110_4_reg_1584_pp0_iter6_reg;
reg   [23:0] trunc_ln110_4_reg_1584_pp0_iter7_reg;
reg   [23:0] trunc_ln110_4_reg_1584_pp0_iter8_reg;
reg   [23:0] trunc_ln110_4_reg_1584_pp0_iter9_reg;
reg   [23:0] trunc_ln110_5_reg_1589;
reg   [23:0] trunc_ln110_5_reg_1589_pp0_iter2_reg;
reg   [23:0] trunc_ln110_5_reg_1589_pp0_iter3_reg;
reg   [23:0] trunc_ln110_5_reg_1589_pp0_iter4_reg;
reg   [23:0] trunc_ln110_5_reg_1589_pp0_iter5_reg;
reg   [23:0] trunc_ln110_5_reg_1589_pp0_iter6_reg;
reg   [23:0] trunc_ln110_5_reg_1589_pp0_iter7_reg;
reg   [23:0] trunc_ln110_5_reg_1589_pp0_iter8_reg;
reg   [23:0] trunc_ln110_5_reg_1589_pp0_iter9_reg;
reg   [23:0] trunc_ln110_5_reg_1589_pp0_iter10_reg;
reg   [23:0] trunc_ln110_6_reg_1594;
reg   [23:0] trunc_ln110_6_reg_1594_pp0_iter2_reg;
reg   [23:0] trunc_ln110_6_reg_1594_pp0_iter3_reg;
reg   [23:0] trunc_ln110_6_reg_1594_pp0_iter4_reg;
reg   [23:0] trunc_ln110_6_reg_1594_pp0_iter5_reg;
reg   [23:0] trunc_ln110_6_reg_1594_pp0_iter6_reg;
reg   [23:0] trunc_ln110_6_reg_1594_pp0_iter7_reg;
reg   [23:0] trunc_ln110_6_reg_1594_pp0_iter8_reg;
reg   [23:0] trunc_ln110_6_reg_1594_pp0_iter9_reg;
reg   [23:0] trunc_ln110_6_reg_1594_pp0_iter10_reg;
reg   [23:0] trunc_ln110_6_reg_1594_pp0_iter11_reg;
reg   [23:0] trunc_ln110_7_reg_1599;
reg   [23:0] trunc_ln110_7_reg_1599_pp0_iter2_reg;
reg   [23:0] trunc_ln110_7_reg_1599_pp0_iter3_reg;
reg   [23:0] trunc_ln110_7_reg_1599_pp0_iter4_reg;
reg   [23:0] trunc_ln110_7_reg_1599_pp0_iter5_reg;
reg   [23:0] trunc_ln110_7_reg_1599_pp0_iter6_reg;
reg   [23:0] trunc_ln110_7_reg_1599_pp0_iter7_reg;
reg   [23:0] trunc_ln110_7_reg_1599_pp0_iter8_reg;
reg   [23:0] trunc_ln110_7_reg_1599_pp0_iter9_reg;
reg   [23:0] trunc_ln110_7_reg_1599_pp0_iter10_reg;
reg   [23:0] trunc_ln110_7_reg_1599_pp0_iter11_reg;
reg   [23:0] trunc_ln110_7_reg_1599_pp0_iter12_reg;
reg   [23:0] trunc_ln110_8_reg_1604;
reg   [23:0] trunc_ln110_8_reg_1604_pp0_iter2_reg;
reg   [23:0] trunc_ln110_8_reg_1604_pp0_iter3_reg;
reg   [23:0] trunc_ln110_8_reg_1604_pp0_iter4_reg;
reg   [23:0] trunc_ln110_8_reg_1604_pp0_iter5_reg;
reg   [23:0] trunc_ln110_8_reg_1604_pp0_iter6_reg;
reg   [23:0] trunc_ln110_8_reg_1604_pp0_iter7_reg;
reg   [23:0] trunc_ln110_8_reg_1604_pp0_iter8_reg;
reg   [23:0] trunc_ln110_8_reg_1604_pp0_iter9_reg;
reg   [23:0] trunc_ln110_8_reg_1604_pp0_iter10_reg;
reg   [23:0] trunc_ln110_8_reg_1604_pp0_iter11_reg;
reg   [23:0] trunc_ln110_8_reg_1604_pp0_iter12_reg;
reg   [23:0] trunc_ln110_8_reg_1604_pp0_iter13_reg;
reg   [23:0] trunc_ln110_9_reg_1609;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter2_reg;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter3_reg;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter4_reg;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter5_reg;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter6_reg;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter7_reg;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter8_reg;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter9_reg;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter10_reg;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter11_reg;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter12_reg;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter13_reg;
reg   [23:0] trunc_ln110_9_reg_1609_pp0_iter14_reg;
reg   [23:0] trunc_ln110_10_reg_1614;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter2_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter3_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter4_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter5_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter6_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter7_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter8_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter9_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter10_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter11_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter12_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter13_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter14_reg;
reg   [23:0] trunc_ln110_10_reg_1614_pp0_iter15_reg;
reg   [23:0] trunc_ln110_11_reg_1619;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter2_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter3_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter4_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter5_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter6_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter7_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter8_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter9_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter10_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter11_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter12_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter13_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter14_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter15_reg;
reg   [23:0] trunc_ln110_11_reg_1619_pp0_iter16_reg;
reg   [23:0] trunc_ln1_reg_1624;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter2_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter3_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter4_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter5_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter6_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter7_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter8_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter9_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter10_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter11_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter12_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter13_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter14_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter15_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter16_reg;
reg   [23:0] trunc_ln1_reg_1624_pp0_iter17_reg;
wire   [31:0] tmp_x_3_fu_661_p3;
reg   [31:0] tmp_x_3_reg_1629;
wire   [3:0] w_idx_fu_669_p1;
reg   [3:0] w_idx_reg_1635;
wire   [3:0] w_idy_fu_673_p3;
reg   [3:0] w_idy_reg_1640;
wire   [31:0] tmp_x_6_fu_713_p3;
reg   [31:0] tmp_x_6_reg_1652;
wire   [3:0] w_idx_1_fu_721_p1;
reg   [3:0] w_idx_1_reg_1658;
wire   [3:0] w_idy_1_fu_725_p3;
reg   [3:0] w_idy_1_reg_1663;
wire   [23:0] tmp_data_1_saturatedAdd_fu_348_ap_return;
reg   [23:0] tmp_data_1_reg_1670;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter4_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter5_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter6_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter7_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter8_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter9_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter10_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter11_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter12_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter13_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter14_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter15_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter16_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter17_reg;
reg   [23:0] tmp_data_1_reg_1670_pp0_iter18_reg;
wire   [31:0] tmp_x_9_fu_764_p3;
reg   [31:0] tmp_x_9_reg_1680;
wire   [3:0] w_idx_2_fu_772_p1;
reg   [3:0] w_idx_2_reg_1686;
wire   [3:0] w_idy_2_fu_776_p3;
reg   [3:0] w_idy_2_reg_1691;
wire   [23:0] tmp_data_2_saturatedAdd_fu_355_ap_return;
reg   [23:0] tmp_data_2_reg_1698;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter5_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter6_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter7_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter8_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter9_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter10_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter11_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter12_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter13_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter14_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter15_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter16_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter17_reg;
reg   [23:0] tmp_data_2_reg_1698_pp0_iter18_reg;
wire   [31:0] tmp_x_12_fu_815_p3;
reg   [31:0] tmp_x_12_reg_1708;
wire   [3:0] w_idx_3_fu_823_p1;
reg   [3:0] w_idx_3_reg_1714;
wire   [3:0] w_idy_3_fu_827_p3;
reg   [3:0] w_idy_3_reg_1719;
wire   [23:0] tmp_16_i_saturatedAdd_fu_362_ap_return;
reg   [23:0] tmp_16_i_reg_1726;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter6_reg;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter7_reg;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter8_reg;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter9_reg;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter10_reg;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter11_reg;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter12_reg;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter13_reg;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter14_reg;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter15_reg;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter16_reg;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter17_reg;
reg   [23:0] tmp_16_i_reg_1726_pp0_iter18_reg;
wire   [31:0] tmp_x_15_fu_866_p3;
reg   [31:0] tmp_x_15_reg_1736;
wire   [3:0] w_idx_4_fu_874_p1;
reg   [3:0] w_idx_4_reg_1742;
wire   [3:0] w_idy_4_fu_878_p3;
reg   [3:0] w_idy_4_reg_1747;
wire   [23:0] tmp_17_i_saturatedAdd_fu_369_ap_return;
reg   [23:0] tmp_17_i_reg_1754;
reg   [23:0] tmp_17_i_reg_1754_pp0_iter7_reg;
reg   [23:0] tmp_17_i_reg_1754_pp0_iter8_reg;
reg   [23:0] tmp_17_i_reg_1754_pp0_iter9_reg;
reg   [23:0] tmp_17_i_reg_1754_pp0_iter10_reg;
reg   [23:0] tmp_17_i_reg_1754_pp0_iter11_reg;
reg   [23:0] tmp_17_i_reg_1754_pp0_iter12_reg;
reg   [23:0] tmp_17_i_reg_1754_pp0_iter13_reg;
reg   [23:0] tmp_17_i_reg_1754_pp0_iter14_reg;
reg   [23:0] tmp_17_i_reg_1754_pp0_iter15_reg;
reg   [23:0] tmp_17_i_reg_1754_pp0_iter16_reg;
reg   [23:0] tmp_17_i_reg_1754_pp0_iter17_reg;
reg   [23:0] tmp_17_i_reg_1754_pp0_iter18_reg;
wire   [31:0] tmp_x_18_fu_917_p3;
reg   [31:0] tmp_x_18_reg_1764;
wire   [3:0] w_idx_5_fu_925_p1;
reg   [3:0] w_idx_5_reg_1770;
wire   [3:0] w_idy_5_fu_929_p3;
reg   [3:0] w_idy_5_reg_1775;
wire   [23:0] tmp_18_i_saturatedAdd_fu_376_ap_return;
reg   [23:0] tmp_18_i_reg_1782;
reg   [23:0] tmp_18_i_reg_1782_pp0_iter8_reg;
reg   [23:0] tmp_18_i_reg_1782_pp0_iter9_reg;
reg   [23:0] tmp_18_i_reg_1782_pp0_iter10_reg;
reg   [23:0] tmp_18_i_reg_1782_pp0_iter11_reg;
reg   [23:0] tmp_18_i_reg_1782_pp0_iter12_reg;
reg   [23:0] tmp_18_i_reg_1782_pp0_iter13_reg;
reg   [23:0] tmp_18_i_reg_1782_pp0_iter14_reg;
reg   [23:0] tmp_18_i_reg_1782_pp0_iter15_reg;
reg   [23:0] tmp_18_i_reg_1782_pp0_iter16_reg;
reg   [23:0] tmp_18_i_reg_1782_pp0_iter17_reg;
reg   [23:0] tmp_18_i_reg_1782_pp0_iter18_reg;
wire   [31:0] tmp_x_21_fu_968_p3;
reg   [31:0] tmp_x_21_reg_1792;
wire   [3:0] w_idx_6_fu_976_p1;
reg   [3:0] w_idx_6_reg_1798;
wire   [3:0] w_idy_6_fu_980_p3;
reg   [3:0] w_idy_6_reg_1803;
wire   [23:0] tmp_19_i_saturatedAdd_fu_383_ap_return;
reg   [23:0] tmp_19_i_reg_1810;
reg   [23:0] tmp_19_i_reg_1810_pp0_iter9_reg;
reg   [23:0] tmp_19_i_reg_1810_pp0_iter10_reg;
reg   [23:0] tmp_19_i_reg_1810_pp0_iter11_reg;
reg   [23:0] tmp_19_i_reg_1810_pp0_iter12_reg;
reg   [23:0] tmp_19_i_reg_1810_pp0_iter13_reg;
reg   [23:0] tmp_19_i_reg_1810_pp0_iter14_reg;
reg   [23:0] tmp_19_i_reg_1810_pp0_iter15_reg;
reg   [23:0] tmp_19_i_reg_1810_pp0_iter16_reg;
reg   [23:0] tmp_19_i_reg_1810_pp0_iter17_reg;
reg   [23:0] tmp_19_i_reg_1810_pp0_iter18_reg;
wire   [31:0] tmp_x_24_fu_1019_p3;
reg   [31:0] tmp_x_24_reg_1820;
wire   [3:0] w_idx_7_fu_1027_p1;
reg   [3:0] w_idx_7_reg_1826;
wire   [3:0] w_idy_7_fu_1031_p3;
reg   [3:0] w_idy_7_reg_1831;
wire   [23:0] tmp_20_i_saturatedAdd_fu_390_ap_return;
reg   [23:0] tmp_20_i_reg_1838;
reg   [23:0] tmp_20_i_reg_1838_pp0_iter10_reg;
reg   [23:0] tmp_20_i_reg_1838_pp0_iter11_reg;
reg   [23:0] tmp_20_i_reg_1838_pp0_iter12_reg;
reg   [23:0] tmp_20_i_reg_1838_pp0_iter13_reg;
reg   [23:0] tmp_20_i_reg_1838_pp0_iter14_reg;
reg   [23:0] tmp_20_i_reg_1838_pp0_iter15_reg;
reg   [23:0] tmp_20_i_reg_1838_pp0_iter16_reg;
reg   [23:0] tmp_20_i_reg_1838_pp0_iter17_reg;
reg   [23:0] tmp_20_i_reg_1838_pp0_iter18_reg;
wire   [31:0] tmp_x_27_fu_1070_p3;
reg   [31:0] tmp_x_27_reg_1848;
wire   [3:0] w_idx_8_fu_1078_p1;
reg   [3:0] w_idx_8_reg_1854;
wire   [3:0] w_idy_8_fu_1082_p3;
reg   [3:0] w_idy_8_reg_1859;
wire   [23:0] tmp_21_i_saturatedAdd_fu_397_ap_return;
reg   [23:0] tmp_21_i_reg_1866;
reg   [23:0] tmp_21_i_reg_1866_pp0_iter11_reg;
reg   [23:0] tmp_21_i_reg_1866_pp0_iter12_reg;
reg   [23:0] tmp_21_i_reg_1866_pp0_iter13_reg;
reg   [23:0] tmp_21_i_reg_1866_pp0_iter14_reg;
reg   [23:0] tmp_21_i_reg_1866_pp0_iter15_reg;
reg   [23:0] tmp_21_i_reg_1866_pp0_iter16_reg;
reg   [23:0] tmp_21_i_reg_1866_pp0_iter17_reg;
reg   [23:0] tmp_21_i_reg_1866_pp0_iter18_reg;
wire   [31:0] tmp_x_30_fu_1121_p3;
reg   [31:0] tmp_x_30_reg_1876;
wire   [3:0] w_idx_9_fu_1129_p1;
reg   [3:0] w_idx_9_reg_1882;
wire   [3:0] w_idy_9_fu_1133_p3;
reg   [3:0] w_idy_9_reg_1887;
wire   [23:0] tmp_22_i_saturatedAdd_fu_404_ap_return;
reg   [23:0] tmp_22_i_reg_1894;
reg   [23:0] tmp_22_i_reg_1894_pp0_iter12_reg;
reg   [23:0] tmp_22_i_reg_1894_pp0_iter13_reg;
reg   [23:0] tmp_22_i_reg_1894_pp0_iter14_reg;
reg   [23:0] tmp_22_i_reg_1894_pp0_iter15_reg;
reg   [23:0] tmp_22_i_reg_1894_pp0_iter16_reg;
reg   [23:0] tmp_22_i_reg_1894_pp0_iter17_reg;
reg   [23:0] tmp_22_i_reg_1894_pp0_iter18_reg;
wire   [31:0] tmp_x_33_fu_1172_p3;
reg   [31:0] tmp_x_33_reg_1904;
wire   [3:0] w_idx_10_fu_1180_p1;
reg   [3:0] w_idx_10_reg_1910;
wire   [3:0] w_idy_10_fu_1184_p3;
reg   [3:0] w_idy_10_reg_1915;
wire   [23:0] tmp_23_i_saturatedAdd_fu_411_ap_return;
reg   [23:0] tmp_23_i_reg_1922;
reg   [23:0] tmp_23_i_reg_1922_pp0_iter13_reg;
reg   [23:0] tmp_23_i_reg_1922_pp0_iter14_reg;
reg   [23:0] tmp_23_i_reg_1922_pp0_iter15_reg;
reg   [23:0] tmp_23_i_reg_1922_pp0_iter16_reg;
reg   [23:0] tmp_23_i_reg_1922_pp0_iter17_reg;
reg   [23:0] tmp_23_i_reg_1922_pp0_iter18_reg;
wire   [31:0] tmp_x_36_fu_1223_p3;
reg   [31:0] tmp_x_36_reg_1932;
wire   [3:0] w_idx_11_fu_1231_p1;
reg   [3:0] w_idx_11_reg_1938;
wire   [3:0] w_idy_11_fu_1235_p3;
reg   [3:0] w_idy_11_reg_1943;
wire   [23:0] tmp_24_i_saturatedAdd_fu_418_ap_return;
reg   [23:0] tmp_24_i_reg_1950;
reg   [23:0] tmp_24_i_reg_1950_pp0_iter14_reg;
reg   [23:0] tmp_24_i_reg_1950_pp0_iter15_reg;
reg   [23:0] tmp_24_i_reg_1950_pp0_iter16_reg;
reg   [23:0] tmp_24_i_reg_1950_pp0_iter17_reg;
reg   [23:0] tmp_24_i_reg_1950_pp0_iter18_reg;
wire   [31:0] tmp_x_39_fu_1274_p3;
reg   [31:0] tmp_x_39_reg_1960;
wire   [3:0] w_idx_12_fu_1282_p1;
reg   [3:0] w_idx_12_reg_1966;
wire   [3:0] w_idy_12_fu_1286_p3;
reg   [3:0] w_idy_12_reg_1971;
wire   [23:0] tmp_25_i_saturatedAdd_fu_425_ap_return;
reg   [23:0] tmp_25_i_reg_1978;
reg   [23:0] tmp_25_i_reg_1978_pp0_iter15_reg;
reg   [23:0] tmp_25_i_reg_1978_pp0_iter16_reg;
reg   [23:0] tmp_25_i_reg_1978_pp0_iter17_reg;
reg   [23:0] tmp_25_i_reg_1978_pp0_iter18_reg;
wire   [31:0] tmp_x_42_fu_1325_p3;
reg   [31:0] tmp_x_42_reg_1988;
wire   [3:0] w_idx_13_fu_1333_p1;
reg   [3:0] w_idx_13_reg_1994;
wire   [3:0] w_idy_13_fu_1337_p3;
reg   [3:0] w_idy_13_reg_1999;
wire   [23:0] tmp_26_i_saturatedAdd_fu_432_ap_return;
reg   [23:0] tmp_26_i_reg_2006;
reg   [23:0] tmp_26_i_reg_2006_pp0_iter16_reg;
reg   [23:0] tmp_26_i_reg_2006_pp0_iter17_reg;
reg   [23:0] tmp_26_i_reg_2006_pp0_iter18_reg;
wire   [31:0] tmp_x_45_fu_1376_p3;
reg   [31:0] tmp_x_45_reg_2016;
wire   [3:0] w_idx_14_fu_1384_p1;
reg   [3:0] w_idx_14_reg_2021;
wire   [3:0] w_idy_14_fu_1388_p3;
reg   [3:0] w_idy_14_reg_2027;
wire   [23:0] tmp_27_i_saturatedAdd_fu_439_ap_return;
reg   [23:0] tmp_27_i_reg_2034;
reg   [23:0] tmp_27_i_reg_2034_pp0_iter17_reg;
reg   [23:0] tmp_27_i_reg_2034_pp0_iter18_reg;
wire   [3:0] tmp_x_fu_1430_p2;
reg   [3:0] tmp_x_reg_2044;
wire   [3:0] select_ln119_31_fu_1435_p3;
reg   [3:0] select_ln119_31_reg_2049;
wire   [23:0] tmp_28_i_saturatedAdd_fu_446_ap_return;
reg   [23:0] tmp_28_i_reg_2054;
reg   [23:0] tmp_28_i_reg_2054_pp0_iter18_reg;
wire   [23:0] tmp_29_i_saturatedAdd_fu_453_ap_return;
reg   [23:0] tmp_29_i_reg_2064;
wire    tmp_data_1_saturatedAdd_fu_348_ap_ready;
wire    tmp_data_2_saturatedAdd_fu_355_ap_ready;
wire    tmp_16_i_saturatedAdd_fu_362_ap_ready;
wire    tmp_17_i_saturatedAdd_fu_369_ap_ready;
wire    tmp_18_i_saturatedAdd_fu_376_ap_ready;
wire    tmp_19_i_saturatedAdd_fu_383_ap_ready;
wire    tmp_20_i_saturatedAdd_fu_390_ap_ready;
wire    tmp_21_i_saturatedAdd_fu_397_ap_ready;
wire    tmp_22_i_saturatedAdd_fu_404_ap_ready;
wire    tmp_23_i_saturatedAdd_fu_411_ap_ready;
wire    tmp_24_i_saturatedAdd_fu_418_ap_ready;
wire    tmp_25_i_saturatedAdd_fu_425_ap_ready;
wire    tmp_26_i_saturatedAdd_fu_432_ap_ready;
wire    tmp_27_i_saturatedAdd_fu_439_ap_ready;
wire    tmp_28_i_saturatedAdd_fu_446_ap_ready;
wire    tmp_29_i_saturatedAdd_fu_453_ap_ready;
wire   [63:0] zext_ln126_fu_687_p1;
wire   [63:0] zext_ln126_1_fu_738_p1;
wire   [63:0] zext_ln126_2_fu_789_p1;
wire   [63:0] zext_ln126_3_fu_840_p1;
wire   [63:0] zext_ln126_4_fu_891_p1;
wire   [63:0] zext_ln126_5_fu_942_p1;
wire   [63:0] zext_ln126_6_fu_993_p1;
wire   [63:0] zext_ln126_7_fu_1044_p1;
wire   [63:0] zext_ln126_8_fu_1095_p1;
wire   [63:0] zext_ln126_9_fu_1146_p1;
wire   [63:0] zext_ln126_10_fu_1197_p1;
wire   [63:0] zext_ln126_11_fu_1248_p1;
wire   [63:0] zext_ln126_12_fu_1299_p1;
wire   [63:0] zext_ln126_13_fu_1350_p1;
wire   [63:0] zext_ln126_14_fu_1401_p1;
wire   [63:0] zext_ln126_15_fu_1448_p1;
reg   [14:0] idx_fu_126;
wire   [14:0] idx_3_fu_474_p2;
wire    ap_loop_init;
reg   [14:0] ap_sig_allocacmp_idx_2;
reg    ap_block_pp0_stage0_01001;
wire   [3:0] trunc_ln155_fu_639_p1;
wire   [0:0] icmp_ln119_fu_643_p2;
wire   [31:0] tmp_x_2_fu_649_p2;
wire   [3:0] tmp_y_1_fu_655_p2;
wire   [7:0] tmp_3_fu_681_p3;
wire   [31:0] tmp_x_4_fu_692_p2;
wire   [0:0] icmp_ln119_1_fu_697_p2;
wire   [31:0] tmp_x_5_fu_703_p2;
wire   [3:0] tmp_y_3_fu_708_p2;
wire   [7:0] tmp_4_fu_732_p3;
wire   [31:0] tmp_x_7_fu_743_p2;
wire   [0:0] icmp_ln119_2_fu_748_p2;
wire   [31:0] tmp_x_8_fu_754_p2;
wire   [3:0] tmp_y_5_fu_759_p2;
wire   [7:0] tmp_5_fu_783_p3;
wire   [31:0] tmp_x_10_fu_794_p2;
wire   [0:0] icmp_ln119_3_fu_799_p2;
wire   [31:0] tmp_x_11_fu_805_p2;
wire   [3:0] tmp_y_7_fu_810_p2;
wire   [7:0] tmp_6_fu_834_p3;
wire   [31:0] tmp_x_13_fu_845_p2;
wire   [0:0] icmp_ln119_4_fu_850_p2;
wire   [31:0] tmp_x_14_fu_856_p2;
wire   [3:0] tmp_y_9_fu_861_p2;
wire   [7:0] tmp_7_fu_885_p3;
wire   [31:0] tmp_x_16_fu_896_p2;
wire   [0:0] icmp_ln119_5_fu_901_p2;
wire   [31:0] tmp_x_17_fu_907_p2;
wire   [3:0] tmp_y_11_fu_912_p2;
wire   [7:0] tmp_8_fu_936_p3;
wire   [31:0] tmp_x_19_fu_947_p2;
wire   [0:0] icmp_ln119_6_fu_952_p2;
wire   [31:0] tmp_x_20_fu_958_p2;
wire   [3:0] tmp_y_13_fu_963_p2;
wire   [7:0] tmp_9_fu_987_p3;
wire   [31:0] tmp_x_22_fu_998_p2;
wire   [0:0] icmp_ln119_7_fu_1003_p2;
wire   [31:0] tmp_x_23_fu_1009_p2;
wire   [3:0] tmp_y_15_fu_1014_p2;
wire   [7:0] tmp_s_fu_1038_p3;
wire   [31:0] tmp_x_25_fu_1049_p2;
wire   [0:0] icmp_ln119_8_fu_1054_p2;
wire   [31:0] tmp_x_26_fu_1060_p2;
wire   [3:0] tmp_y_17_fu_1065_p2;
wire   [7:0] tmp_1_fu_1089_p3;
wire   [31:0] tmp_x_28_fu_1100_p2;
wire   [0:0] icmp_ln119_9_fu_1105_p2;
wire   [31:0] tmp_x_29_fu_1111_p2;
wire   [3:0] tmp_y_19_fu_1116_p2;
wire   [7:0] tmp_2_fu_1140_p3;
wire   [31:0] tmp_x_31_fu_1151_p2;
wire   [0:0] icmp_ln119_10_fu_1156_p2;
wire   [31:0] tmp_x_32_fu_1162_p2;
wire   [3:0] tmp_y_21_fu_1167_p2;
wire   [7:0] tmp_10_fu_1191_p3;
wire   [31:0] tmp_x_34_fu_1202_p2;
wire   [0:0] icmp_ln119_11_fu_1207_p2;
wire   [31:0] tmp_x_35_fu_1213_p2;
wire   [3:0] tmp_y_23_fu_1218_p2;
wire   [7:0] tmp_11_fu_1242_p3;
wire   [31:0] tmp_x_37_fu_1253_p2;
wire   [0:0] icmp_ln119_12_fu_1258_p2;
wire   [31:0] tmp_x_38_fu_1264_p2;
wire   [3:0] tmp_y_25_fu_1269_p2;
wire   [7:0] tmp_12_fu_1293_p3;
wire   [31:0] tmp_x_40_fu_1304_p2;
wire   [0:0] icmp_ln119_13_fu_1309_p2;
wire   [31:0] tmp_x_41_fu_1315_p2;
wire   [3:0] tmp_y_27_fu_1320_p2;
wire   [7:0] tmp_13_fu_1344_p3;
wire   [31:0] tmp_x_43_fu_1355_p2;
wire   [0:0] icmp_ln119_14_fu_1360_p2;
wire   [31:0] tmp_x_44_fu_1366_p2;
wire   [3:0] tmp_y_29_fu_1371_p2;
wire   [7:0] tmp_14_fu_1395_p3;
wire   [31:0] tmp_x_46_fu_1406_p2;
wire   [0:0] icmp_ln119_15_fu_1411_p2;
wire   [3:0] select_ln119_fu_1422_p3;
wire   [3:0] tmp_y_31_fu_1417_p2;
wire   [7:0] tmp_15_fu_1442_p3;
wire   [31:0] zext_ln128_12_fu_1495_p1;
wire   [31:0] zext_ln128_11_fu_1492_p1;
wire   [31:0] zext_ln128_10_fu_1489_p1;
wire   [31:0] zext_ln128_9_fu_1486_p1;
wire   [31:0] zext_ln128_8_fu_1483_p1;
wire   [31:0] zext_ln128_7_fu_1480_p1;
wire   [31:0] zext_ln128_6_fu_1477_p1;
wire   [31:0] zext_ln128_5_fu_1474_p1;
wire   [31:0] zext_ln128_4_fu_1471_p1;
wire   [31:0] zext_ln128_3_fu_1468_p1;
wire   [31:0] zext_ln128_2_fu_1465_p1;
wire   [31:0] zext_ln128_1_fu_1462_p1;
wire   [31:0] zext_ln128_fu_1459_p1;
wire   [31:0] zext_ln105_1_fu_1456_p1;
wire   [31:0] zext_ln105_fu_1453_p1;
wire   [503:0] or_ln174_i_fu_1498_p17;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_859;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_done_reg = 1'b0;
end

apply_watermark_compute_watermark_watermark_ROM_AUTO_1R #(
    .DataWidth( 17 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
watermark_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(watermark_address0),
    .ce0(watermark_ce0),
    .q0(watermark_q0),
    .address1(watermark_address1),
    .ce1(watermark_ce1),
    .q1(watermark_q1),
    .address2(watermark_address2),
    .ce2(watermark_ce2),
    .q2(watermark_q2),
    .address3(watermark_address3),
    .ce3(watermark_ce3),
    .q3(watermark_q3),
    .address4(watermark_address4),
    .ce4(watermark_ce4),
    .q4(watermark_q4),
    .address5(watermark_address5),
    .ce5(watermark_ce5),
    .q5(watermark_q5),
    .address6(watermark_address6),
    .ce6(watermark_ce6),
    .q6(watermark_q6),
    .address7(watermark_address7),
    .ce7(watermark_ce7),
    .q7(watermark_q7),
    .address8(watermark_address8),
    .ce8(watermark_ce8),
    .q8(watermark_q8),
    .address9(watermark_address9),
    .ce9(watermark_ce9),
    .q9(watermark_q9),
    .address10(watermark_address10),
    .ce10(watermark_ce10),
    .q10(watermark_q10),
    .address11(watermark_address11),
    .ce11(watermark_ce11),
    .q11(watermark_q11),
    .address12(watermark_address12),
    .ce12(watermark_ce12),
    .q12(watermark_q12),
    .address13(watermark_address13),
    .ce13(watermark_ce13),
    .q13(watermark_q13),
    .address14(watermark_address14),
    .ce14(watermark_ce14),
    .q14(watermark_q14),
    .address15(watermark_address15),
    .ce15(watermark_ce15),
    .q15(watermark_q15)
);

apply_watermark_saturatedAdd tmp_data_1_saturatedAdd_fu_348(
    .ap_ready(tmp_data_1_saturatedAdd_fu_348_ap_ready),
    .x(tmp_data_reg_1549_pp0_iter2_reg),
    .y(watermark_q15),
    .ap_return(tmp_data_1_saturatedAdd_fu_348_ap_return)
);

apply_watermark_saturatedAdd tmp_data_2_saturatedAdd_fu_355(
    .ap_ready(tmp_data_2_saturatedAdd_fu_355_ap_ready),
    .x(trunc_ln4_reg_1554_pp0_iter3_reg),
    .y(watermark_q14),
    .ap_return(tmp_data_2_saturatedAdd_fu_355_ap_return)
);

apply_watermark_saturatedAdd tmp_16_i_saturatedAdd_fu_362(
    .ap_ready(tmp_16_i_saturatedAdd_fu_362_ap_ready),
    .x(trunc_ln_reg_1559_pp0_iter4_reg),
    .y(watermark_q13),
    .ap_return(tmp_16_i_saturatedAdd_fu_362_ap_return)
);

apply_watermark_saturatedAdd tmp_17_i_saturatedAdd_fu_369(
    .ap_ready(tmp_17_i_saturatedAdd_fu_369_ap_ready),
    .x(trunc_ln110_s_reg_1564_pp0_iter5_reg),
    .y(watermark_q12),
    .ap_return(tmp_17_i_saturatedAdd_fu_369_ap_return)
);

apply_watermark_saturatedAdd tmp_18_i_saturatedAdd_fu_376(
    .ap_ready(tmp_18_i_saturatedAdd_fu_376_ap_ready),
    .x(trunc_ln110_1_reg_1569_pp0_iter6_reg),
    .y(watermark_q11),
    .ap_return(tmp_18_i_saturatedAdd_fu_376_ap_return)
);

apply_watermark_saturatedAdd tmp_19_i_saturatedAdd_fu_383(
    .ap_ready(tmp_19_i_saturatedAdd_fu_383_ap_ready),
    .x(trunc_ln110_2_reg_1574_pp0_iter7_reg),
    .y(watermark_q10),
    .ap_return(tmp_19_i_saturatedAdd_fu_383_ap_return)
);

apply_watermark_saturatedAdd tmp_20_i_saturatedAdd_fu_390(
    .ap_ready(tmp_20_i_saturatedAdd_fu_390_ap_ready),
    .x(trunc_ln110_3_reg_1579_pp0_iter8_reg),
    .y(watermark_q9),
    .ap_return(tmp_20_i_saturatedAdd_fu_390_ap_return)
);

apply_watermark_saturatedAdd tmp_21_i_saturatedAdd_fu_397(
    .ap_ready(tmp_21_i_saturatedAdd_fu_397_ap_ready),
    .x(trunc_ln110_4_reg_1584_pp0_iter9_reg),
    .y(watermark_q8),
    .ap_return(tmp_21_i_saturatedAdd_fu_397_ap_return)
);

apply_watermark_saturatedAdd tmp_22_i_saturatedAdd_fu_404(
    .ap_ready(tmp_22_i_saturatedAdd_fu_404_ap_ready),
    .x(trunc_ln110_5_reg_1589_pp0_iter10_reg),
    .y(watermark_q7),
    .ap_return(tmp_22_i_saturatedAdd_fu_404_ap_return)
);

apply_watermark_saturatedAdd tmp_23_i_saturatedAdd_fu_411(
    .ap_ready(tmp_23_i_saturatedAdd_fu_411_ap_ready),
    .x(trunc_ln110_6_reg_1594_pp0_iter11_reg),
    .y(watermark_q6),
    .ap_return(tmp_23_i_saturatedAdd_fu_411_ap_return)
);

apply_watermark_saturatedAdd tmp_24_i_saturatedAdd_fu_418(
    .ap_ready(tmp_24_i_saturatedAdd_fu_418_ap_ready),
    .x(trunc_ln110_7_reg_1599_pp0_iter12_reg),
    .y(watermark_q5),
    .ap_return(tmp_24_i_saturatedAdd_fu_418_ap_return)
);

apply_watermark_saturatedAdd tmp_25_i_saturatedAdd_fu_425(
    .ap_ready(tmp_25_i_saturatedAdd_fu_425_ap_ready),
    .x(trunc_ln110_8_reg_1604_pp0_iter13_reg),
    .y(watermark_q4),
    .ap_return(tmp_25_i_saturatedAdd_fu_425_ap_return)
);

apply_watermark_saturatedAdd tmp_26_i_saturatedAdd_fu_432(
    .ap_ready(tmp_26_i_saturatedAdd_fu_432_ap_ready),
    .x(trunc_ln110_9_reg_1609_pp0_iter14_reg),
    .y(watermark_q3),
    .ap_return(tmp_26_i_saturatedAdd_fu_432_ap_return)
);

apply_watermark_saturatedAdd tmp_27_i_saturatedAdd_fu_439(
    .ap_ready(tmp_27_i_saturatedAdd_fu_439_ap_ready),
    .x(trunc_ln110_10_reg_1614_pp0_iter15_reg),
    .y(watermark_q2),
    .ap_return(tmp_27_i_saturatedAdd_fu_439_ap_return)
);

apply_watermark_saturatedAdd tmp_28_i_saturatedAdd_fu_446(
    .ap_ready(tmp_28_i_saturatedAdd_fu_446_ap_ready),
    .x(trunc_ln110_11_reg_1619_pp0_iter16_reg),
    .y(watermark_q1),
    .ap_return(tmp_28_i_saturatedAdd_fu_446_ap_return)
);

apply_watermark_saturatedAdd tmp_29_i_saturatedAdd_fu_453(
    .ap_ready(tmp_29_i_saturatedAdd_fu_453_ap_ready),
    .x(trunc_ln1_reg_1624_pp0_iter17_reg),
    .y(watermark_q0),
    .ap_return(tmp_29_i_saturatedAdd_fu_453_ap_return)
);

apply_watermark_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_859)) begin
        if ((icmp_ln107_fu_468_p2 == 1'd0)) begin
            idx_fu_126 <= idx_3_fu_474_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            idx_fu_126 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        select_ln119_31_reg_2049 <= select_ln119_31_fu_1435_p3;
        tmp_16_i_reg_1726 <= tmp_16_i_saturatedAdd_fu_362_ap_return;
        tmp_16_i_reg_1726_pp0_iter10_reg <= tmp_16_i_reg_1726_pp0_iter9_reg;
        tmp_16_i_reg_1726_pp0_iter11_reg <= tmp_16_i_reg_1726_pp0_iter10_reg;
        tmp_16_i_reg_1726_pp0_iter12_reg <= tmp_16_i_reg_1726_pp0_iter11_reg;
        tmp_16_i_reg_1726_pp0_iter13_reg <= tmp_16_i_reg_1726_pp0_iter12_reg;
        tmp_16_i_reg_1726_pp0_iter14_reg <= tmp_16_i_reg_1726_pp0_iter13_reg;
        tmp_16_i_reg_1726_pp0_iter15_reg <= tmp_16_i_reg_1726_pp0_iter14_reg;
        tmp_16_i_reg_1726_pp0_iter16_reg <= tmp_16_i_reg_1726_pp0_iter15_reg;
        tmp_16_i_reg_1726_pp0_iter17_reg <= tmp_16_i_reg_1726_pp0_iter16_reg;
        tmp_16_i_reg_1726_pp0_iter18_reg <= tmp_16_i_reg_1726_pp0_iter17_reg;
        tmp_16_i_reg_1726_pp0_iter6_reg <= tmp_16_i_reg_1726;
        tmp_16_i_reg_1726_pp0_iter7_reg <= tmp_16_i_reg_1726_pp0_iter6_reg;
        tmp_16_i_reg_1726_pp0_iter8_reg <= tmp_16_i_reg_1726_pp0_iter7_reg;
        tmp_16_i_reg_1726_pp0_iter9_reg <= tmp_16_i_reg_1726_pp0_iter8_reg;
        tmp_17_i_reg_1754 <= tmp_17_i_saturatedAdd_fu_369_ap_return;
        tmp_17_i_reg_1754_pp0_iter10_reg <= tmp_17_i_reg_1754_pp0_iter9_reg;
        tmp_17_i_reg_1754_pp0_iter11_reg <= tmp_17_i_reg_1754_pp0_iter10_reg;
        tmp_17_i_reg_1754_pp0_iter12_reg <= tmp_17_i_reg_1754_pp0_iter11_reg;
        tmp_17_i_reg_1754_pp0_iter13_reg <= tmp_17_i_reg_1754_pp0_iter12_reg;
        tmp_17_i_reg_1754_pp0_iter14_reg <= tmp_17_i_reg_1754_pp0_iter13_reg;
        tmp_17_i_reg_1754_pp0_iter15_reg <= tmp_17_i_reg_1754_pp0_iter14_reg;
        tmp_17_i_reg_1754_pp0_iter16_reg <= tmp_17_i_reg_1754_pp0_iter15_reg;
        tmp_17_i_reg_1754_pp0_iter17_reg <= tmp_17_i_reg_1754_pp0_iter16_reg;
        tmp_17_i_reg_1754_pp0_iter18_reg <= tmp_17_i_reg_1754_pp0_iter17_reg;
        tmp_17_i_reg_1754_pp0_iter7_reg <= tmp_17_i_reg_1754;
        tmp_17_i_reg_1754_pp0_iter8_reg <= tmp_17_i_reg_1754_pp0_iter7_reg;
        tmp_17_i_reg_1754_pp0_iter9_reg <= tmp_17_i_reg_1754_pp0_iter8_reg;
        tmp_18_i_reg_1782 <= tmp_18_i_saturatedAdd_fu_376_ap_return;
        tmp_18_i_reg_1782_pp0_iter10_reg <= tmp_18_i_reg_1782_pp0_iter9_reg;
        tmp_18_i_reg_1782_pp0_iter11_reg <= tmp_18_i_reg_1782_pp0_iter10_reg;
        tmp_18_i_reg_1782_pp0_iter12_reg <= tmp_18_i_reg_1782_pp0_iter11_reg;
        tmp_18_i_reg_1782_pp0_iter13_reg <= tmp_18_i_reg_1782_pp0_iter12_reg;
        tmp_18_i_reg_1782_pp0_iter14_reg <= tmp_18_i_reg_1782_pp0_iter13_reg;
        tmp_18_i_reg_1782_pp0_iter15_reg <= tmp_18_i_reg_1782_pp0_iter14_reg;
        tmp_18_i_reg_1782_pp0_iter16_reg <= tmp_18_i_reg_1782_pp0_iter15_reg;
        tmp_18_i_reg_1782_pp0_iter17_reg <= tmp_18_i_reg_1782_pp0_iter16_reg;
        tmp_18_i_reg_1782_pp0_iter18_reg <= tmp_18_i_reg_1782_pp0_iter17_reg;
        tmp_18_i_reg_1782_pp0_iter8_reg <= tmp_18_i_reg_1782;
        tmp_18_i_reg_1782_pp0_iter9_reg <= tmp_18_i_reg_1782_pp0_iter8_reg;
        tmp_19_i_reg_1810 <= tmp_19_i_saturatedAdd_fu_383_ap_return;
        tmp_19_i_reg_1810_pp0_iter10_reg <= tmp_19_i_reg_1810_pp0_iter9_reg;
        tmp_19_i_reg_1810_pp0_iter11_reg <= tmp_19_i_reg_1810_pp0_iter10_reg;
        tmp_19_i_reg_1810_pp0_iter12_reg <= tmp_19_i_reg_1810_pp0_iter11_reg;
        tmp_19_i_reg_1810_pp0_iter13_reg <= tmp_19_i_reg_1810_pp0_iter12_reg;
        tmp_19_i_reg_1810_pp0_iter14_reg <= tmp_19_i_reg_1810_pp0_iter13_reg;
        tmp_19_i_reg_1810_pp0_iter15_reg <= tmp_19_i_reg_1810_pp0_iter14_reg;
        tmp_19_i_reg_1810_pp0_iter16_reg <= tmp_19_i_reg_1810_pp0_iter15_reg;
        tmp_19_i_reg_1810_pp0_iter17_reg <= tmp_19_i_reg_1810_pp0_iter16_reg;
        tmp_19_i_reg_1810_pp0_iter18_reg <= tmp_19_i_reg_1810_pp0_iter17_reg;
        tmp_19_i_reg_1810_pp0_iter9_reg <= tmp_19_i_reg_1810;
        tmp_20_i_reg_1838 <= tmp_20_i_saturatedAdd_fu_390_ap_return;
        tmp_20_i_reg_1838_pp0_iter10_reg <= tmp_20_i_reg_1838;
        tmp_20_i_reg_1838_pp0_iter11_reg <= tmp_20_i_reg_1838_pp0_iter10_reg;
        tmp_20_i_reg_1838_pp0_iter12_reg <= tmp_20_i_reg_1838_pp0_iter11_reg;
        tmp_20_i_reg_1838_pp0_iter13_reg <= tmp_20_i_reg_1838_pp0_iter12_reg;
        tmp_20_i_reg_1838_pp0_iter14_reg <= tmp_20_i_reg_1838_pp0_iter13_reg;
        tmp_20_i_reg_1838_pp0_iter15_reg <= tmp_20_i_reg_1838_pp0_iter14_reg;
        tmp_20_i_reg_1838_pp0_iter16_reg <= tmp_20_i_reg_1838_pp0_iter15_reg;
        tmp_20_i_reg_1838_pp0_iter17_reg <= tmp_20_i_reg_1838_pp0_iter16_reg;
        tmp_20_i_reg_1838_pp0_iter18_reg <= tmp_20_i_reg_1838_pp0_iter17_reg;
        tmp_21_i_reg_1866 <= tmp_21_i_saturatedAdd_fu_397_ap_return;
        tmp_21_i_reg_1866_pp0_iter11_reg <= tmp_21_i_reg_1866;
        tmp_21_i_reg_1866_pp0_iter12_reg <= tmp_21_i_reg_1866_pp0_iter11_reg;
        tmp_21_i_reg_1866_pp0_iter13_reg <= tmp_21_i_reg_1866_pp0_iter12_reg;
        tmp_21_i_reg_1866_pp0_iter14_reg <= tmp_21_i_reg_1866_pp0_iter13_reg;
        tmp_21_i_reg_1866_pp0_iter15_reg <= tmp_21_i_reg_1866_pp0_iter14_reg;
        tmp_21_i_reg_1866_pp0_iter16_reg <= tmp_21_i_reg_1866_pp0_iter15_reg;
        tmp_21_i_reg_1866_pp0_iter17_reg <= tmp_21_i_reg_1866_pp0_iter16_reg;
        tmp_21_i_reg_1866_pp0_iter18_reg <= tmp_21_i_reg_1866_pp0_iter17_reg;
        tmp_22_i_reg_1894 <= tmp_22_i_saturatedAdd_fu_404_ap_return;
        tmp_22_i_reg_1894_pp0_iter12_reg <= tmp_22_i_reg_1894;
        tmp_22_i_reg_1894_pp0_iter13_reg <= tmp_22_i_reg_1894_pp0_iter12_reg;
        tmp_22_i_reg_1894_pp0_iter14_reg <= tmp_22_i_reg_1894_pp0_iter13_reg;
        tmp_22_i_reg_1894_pp0_iter15_reg <= tmp_22_i_reg_1894_pp0_iter14_reg;
        tmp_22_i_reg_1894_pp0_iter16_reg <= tmp_22_i_reg_1894_pp0_iter15_reg;
        tmp_22_i_reg_1894_pp0_iter17_reg <= tmp_22_i_reg_1894_pp0_iter16_reg;
        tmp_22_i_reg_1894_pp0_iter18_reg <= tmp_22_i_reg_1894_pp0_iter17_reg;
        tmp_23_i_reg_1922 <= tmp_23_i_saturatedAdd_fu_411_ap_return;
        tmp_23_i_reg_1922_pp0_iter13_reg <= tmp_23_i_reg_1922;
        tmp_23_i_reg_1922_pp0_iter14_reg <= tmp_23_i_reg_1922_pp0_iter13_reg;
        tmp_23_i_reg_1922_pp0_iter15_reg <= tmp_23_i_reg_1922_pp0_iter14_reg;
        tmp_23_i_reg_1922_pp0_iter16_reg <= tmp_23_i_reg_1922_pp0_iter15_reg;
        tmp_23_i_reg_1922_pp0_iter17_reg <= tmp_23_i_reg_1922_pp0_iter16_reg;
        tmp_23_i_reg_1922_pp0_iter18_reg <= tmp_23_i_reg_1922_pp0_iter17_reg;
        tmp_24_i_reg_1950 <= tmp_24_i_saturatedAdd_fu_418_ap_return;
        tmp_24_i_reg_1950_pp0_iter14_reg <= tmp_24_i_reg_1950;
        tmp_24_i_reg_1950_pp0_iter15_reg <= tmp_24_i_reg_1950_pp0_iter14_reg;
        tmp_24_i_reg_1950_pp0_iter16_reg <= tmp_24_i_reg_1950_pp0_iter15_reg;
        tmp_24_i_reg_1950_pp0_iter17_reg <= tmp_24_i_reg_1950_pp0_iter16_reg;
        tmp_24_i_reg_1950_pp0_iter18_reg <= tmp_24_i_reg_1950_pp0_iter17_reg;
        tmp_25_i_reg_1978 <= tmp_25_i_saturatedAdd_fu_425_ap_return;
        tmp_25_i_reg_1978_pp0_iter15_reg <= tmp_25_i_reg_1978;
        tmp_25_i_reg_1978_pp0_iter16_reg <= tmp_25_i_reg_1978_pp0_iter15_reg;
        tmp_25_i_reg_1978_pp0_iter17_reg <= tmp_25_i_reg_1978_pp0_iter16_reg;
        tmp_25_i_reg_1978_pp0_iter18_reg <= tmp_25_i_reg_1978_pp0_iter17_reg;
        tmp_26_i_reg_2006 <= tmp_26_i_saturatedAdd_fu_432_ap_return;
        tmp_26_i_reg_2006_pp0_iter16_reg <= tmp_26_i_reg_2006;
        tmp_26_i_reg_2006_pp0_iter17_reg <= tmp_26_i_reg_2006_pp0_iter16_reg;
        tmp_26_i_reg_2006_pp0_iter18_reg <= tmp_26_i_reg_2006_pp0_iter17_reg;
        tmp_27_i_reg_2034 <= tmp_27_i_saturatedAdd_fu_439_ap_return;
        tmp_27_i_reg_2034_pp0_iter17_reg <= tmp_27_i_reg_2034;
        tmp_27_i_reg_2034_pp0_iter18_reg <= tmp_27_i_reg_2034_pp0_iter17_reg;
        tmp_28_i_reg_2054 <= tmp_28_i_saturatedAdd_fu_446_ap_return;
        tmp_28_i_reg_2054_pp0_iter18_reg <= tmp_28_i_reg_2054;
        tmp_29_i_reg_2064 <= tmp_29_i_saturatedAdd_fu_453_ap_return;
        tmp_data_1_reg_1670 <= tmp_data_1_saturatedAdd_fu_348_ap_return;
        tmp_data_1_reg_1670_pp0_iter10_reg <= tmp_data_1_reg_1670_pp0_iter9_reg;
        tmp_data_1_reg_1670_pp0_iter11_reg <= tmp_data_1_reg_1670_pp0_iter10_reg;
        tmp_data_1_reg_1670_pp0_iter12_reg <= tmp_data_1_reg_1670_pp0_iter11_reg;
        tmp_data_1_reg_1670_pp0_iter13_reg <= tmp_data_1_reg_1670_pp0_iter12_reg;
        tmp_data_1_reg_1670_pp0_iter14_reg <= tmp_data_1_reg_1670_pp0_iter13_reg;
        tmp_data_1_reg_1670_pp0_iter15_reg <= tmp_data_1_reg_1670_pp0_iter14_reg;
        tmp_data_1_reg_1670_pp0_iter16_reg <= tmp_data_1_reg_1670_pp0_iter15_reg;
        tmp_data_1_reg_1670_pp0_iter17_reg <= tmp_data_1_reg_1670_pp0_iter16_reg;
        tmp_data_1_reg_1670_pp0_iter18_reg <= tmp_data_1_reg_1670_pp0_iter17_reg;
        tmp_data_1_reg_1670_pp0_iter4_reg <= tmp_data_1_reg_1670;
        tmp_data_1_reg_1670_pp0_iter5_reg <= tmp_data_1_reg_1670_pp0_iter4_reg;
        tmp_data_1_reg_1670_pp0_iter6_reg <= tmp_data_1_reg_1670_pp0_iter5_reg;
        tmp_data_1_reg_1670_pp0_iter7_reg <= tmp_data_1_reg_1670_pp0_iter6_reg;
        tmp_data_1_reg_1670_pp0_iter8_reg <= tmp_data_1_reg_1670_pp0_iter7_reg;
        tmp_data_1_reg_1670_pp0_iter9_reg <= tmp_data_1_reg_1670_pp0_iter8_reg;
        tmp_data_2_reg_1698 <= tmp_data_2_saturatedAdd_fu_355_ap_return;
        tmp_data_2_reg_1698_pp0_iter10_reg <= tmp_data_2_reg_1698_pp0_iter9_reg;
        tmp_data_2_reg_1698_pp0_iter11_reg <= tmp_data_2_reg_1698_pp0_iter10_reg;
        tmp_data_2_reg_1698_pp0_iter12_reg <= tmp_data_2_reg_1698_pp0_iter11_reg;
        tmp_data_2_reg_1698_pp0_iter13_reg <= tmp_data_2_reg_1698_pp0_iter12_reg;
        tmp_data_2_reg_1698_pp0_iter14_reg <= tmp_data_2_reg_1698_pp0_iter13_reg;
        tmp_data_2_reg_1698_pp0_iter15_reg <= tmp_data_2_reg_1698_pp0_iter14_reg;
        tmp_data_2_reg_1698_pp0_iter16_reg <= tmp_data_2_reg_1698_pp0_iter15_reg;
        tmp_data_2_reg_1698_pp0_iter17_reg <= tmp_data_2_reg_1698_pp0_iter16_reg;
        tmp_data_2_reg_1698_pp0_iter18_reg <= tmp_data_2_reg_1698_pp0_iter17_reg;
        tmp_data_2_reg_1698_pp0_iter5_reg <= tmp_data_2_reg_1698;
        tmp_data_2_reg_1698_pp0_iter6_reg <= tmp_data_2_reg_1698_pp0_iter5_reg;
        tmp_data_2_reg_1698_pp0_iter7_reg <= tmp_data_2_reg_1698_pp0_iter6_reg;
        tmp_data_2_reg_1698_pp0_iter8_reg <= tmp_data_2_reg_1698_pp0_iter7_reg;
        tmp_data_2_reg_1698_pp0_iter9_reg <= tmp_data_2_reg_1698_pp0_iter8_reg;
        tmp_data_reg_1549_pp0_iter2_reg <= tmp_data_reg_1549;
        tmp_x_12_reg_1708 <= tmp_x_12_fu_815_p3;
        tmp_x_15_reg_1736 <= tmp_x_15_fu_866_p3;
        tmp_x_18_reg_1764 <= tmp_x_18_fu_917_p3;
        tmp_x_21_reg_1792 <= tmp_x_21_fu_968_p3;
        tmp_x_24_reg_1820 <= tmp_x_24_fu_1019_p3;
        tmp_x_27_reg_1848 <= tmp_x_27_fu_1070_p3;
        tmp_x_30_reg_1876 <= tmp_x_30_fu_1121_p3;
        tmp_x_33_reg_1904 <= tmp_x_33_fu_1172_p3;
        tmp_x_36_reg_1932 <= tmp_x_36_fu_1223_p3;
        tmp_x_39_reg_1960 <= tmp_x_39_fu_1274_p3;
        tmp_x_42_reg_1988 <= tmp_x_42_fu_1325_p3;
        tmp_x_45_reg_2016 <= tmp_x_45_fu_1376_p3;
        tmp_x_6_reg_1652 <= tmp_x_6_fu_713_p3;
        tmp_x_9_reg_1680 <= tmp_x_9_fu_764_p3;
        tmp_x_reg_2044 <= tmp_x_fu_1430_p2;
        trunc_ln110_10_reg_1614_pp0_iter10_reg <= trunc_ln110_10_reg_1614_pp0_iter9_reg;
        trunc_ln110_10_reg_1614_pp0_iter11_reg <= trunc_ln110_10_reg_1614_pp0_iter10_reg;
        trunc_ln110_10_reg_1614_pp0_iter12_reg <= trunc_ln110_10_reg_1614_pp0_iter11_reg;
        trunc_ln110_10_reg_1614_pp0_iter13_reg <= trunc_ln110_10_reg_1614_pp0_iter12_reg;
        trunc_ln110_10_reg_1614_pp0_iter14_reg <= trunc_ln110_10_reg_1614_pp0_iter13_reg;
        trunc_ln110_10_reg_1614_pp0_iter15_reg <= trunc_ln110_10_reg_1614_pp0_iter14_reg;
        trunc_ln110_10_reg_1614_pp0_iter2_reg <= trunc_ln110_10_reg_1614;
        trunc_ln110_10_reg_1614_pp0_iter3_reg <= trunc_ln110_10_reg_1614_pp0_iter2_reg;
        trunc_ln110_10_reg_1614_pp0_iter4_reg <= trunc_ln110_10_reg_1614_pp0_iter3_reg;
        trunc_ln110_10_reg_1614_pp0_iter5_reg <= trunc_ln110_10_reg_1614_pp0_iter4_reg;
        trunc_ln110_10_reg_1614_pp0_iter6_reg <= trunc_ln110_10_reg_1614_pp0_iter5_reg;
        trunc_ln110_10_reg_1614_pp0_iter7_reg <= trunc_ln110_10_reg_1614_pp0_iter6_reg;
        trunc_ln110_10_reg_1614_pp0_iter8_reg <= trunc_ln110_10_reg_1614_pp0_iter7_reg;
        trunc_ln110_10_reg_1614_pp0_iter9_reg <= trunc_ln110_10_reg_1614_pp0_iter8_reg;
        trunc_ln110_11_reg_1619_pp0_iter10_reg <= trunc_ln110_11_reg_1619_pp0_iter9_reg;
        trunc_ln110_11_reg_1619_pp0_iter11_reg <= trunc_ln110_11_reg_1619_pp0_iter10_reg;
        trunc_ln110_11_reg_1619_pp0_iter12_reg <= trunc_ln110_11_reg_1619_pp0_iter11_reg;
        trunc_ln110_11_reg_1619_pp0_iter13_reg <= trunc_ln110_11_reg_1619_pp0_iter12_reg;
        trunc_ln110_11_reg_1619_pp0_iter14_reg <= trunc_ln110_11_reg_1619_pp0_iter13_reg;
        trunc_ln110_11_reg_1619_pp0_iter15_reg <= trunc_ln110_11_reg_1619_pp0_iter14_reg;
        trunc_ln110_11_reg_1619_pp0_iter16_reg <= trunc_ln110_11_reg_1619_pp0_iter15_reg;
        trunc_ln110_11_reg_1619_pp0_iter2_reg <= trunc_ln110_11_reg_1619;
        trunc_ln110_11_reg_1619_pp0_iter3_reg <= trunc_ln110_11_reg_1619_pp0_iter2_reg;
        trunc_ln110_11_reg_1619_pp0_iter4_reg <= trunc_ln110_11_reg_1619_pp0_iter3_reg;
        trunc_ln110_11_reg_1619_pp0_iter5_reg <= trunc_ln110_11_reg_1619_pp0_iter4_reg;
        trunc_ln110_11_reg_1619_pp0_iter6_reg <= trunc_ln110_11_reg_1619_pp0_iter5_reg;
        trunc_ln110_11_reg_1619_pp0_iter7_reg <= trunc_ln110_11_reg_1619_pp0_iter6_reg;
        trunc_ln110_11_reg_1619_pp0_iter8_reg <= trunc_ln110_11_reg_1619_pp0_iter7_reg;
        trunc_ln110_11_reg_1619_pp0_iter9_reg <= trunc_ln110_11_reg_1619_pp0_iter8_reg;
        trunc_ln110_1_reg_1569_pp0_iter2_reg <= trunc_ln110_1_reg_1569;
        trunc_ln110_1_reg_1569_pp0_iter3_reg <= trunc_ln110_1_reg_1569_pp0_iter2_reg;
        trunc_ln110_1_reg_1569_pp0_iter4_reg <= trunc_ln110_1_reg_1569_pp0_iter3_reg;
        trunc_ln110_1_reg_1569_pp0_iter5_reg <= trunc_ln110_1_reg_1569_pp0_iter4_reg;
        trunc_ln110_1_reg_1569_pp0_iter6_reg <= trunc_ln110_1_reg_1569_pp0_iter5_reg;
        trunc_ln110_2_reg_1574_pp0_iter2_reg <= trunc_ln110_2_reg_1574;
        trunc_ln110_2_reg_1574_pp0_iter3_reg <= trunc_ln110_2_reg_1574_pp0_iter2_reg;
        trunc_ln110_2_reg_1574_pp0_iter4_reg <= trunc_ln110_2_reg_1574_pp0_iter3_reg;
        trunc_ln110_2_reg_1574_pp0_iter5_reg <= trunc_ln110_2_reg_1574_pp0_iter4_reg;
        trunc_ln110_2_reg_1574_pp0_iter6_reg <= trunc_ln110_2_reg_1574_pp0_iter5_reg;
        trunc_ln110_2_reg_1574_pp0_iter7_reg <= trunc_ln110_2_reg_1574_pp0_iter6_reg;
        trunc_ln110_3_reg_1579_pp0_iter2_reg <= trunc_ln110_3_reg_1579;
        trunc_ln110_3_reg_1579_pp0_iter3_reg <= trunc_ln110_3_reg_1579_pp0_iter2_reg;
        trunc_ln110_3_reg_1579_pp0_iter4_reg <= trunc_ln110_3_reg_1579_pp0_iter3_reg;
        trunc_ln110_3_reg_1579_pp0_iter5_reg <= trunc_ln110_3_reg_1579_pp0_iter4_reg;
        trunc_ln110_3_reg_1579_pp0_iter6_reg <= trunc_ln110_3_reg_1579_pp0_iter5_reg;
        trunc_ln110_3_reg_1579_pp0_iter7_reg <= trunc_ln110_3_reg_1579_pp0_iter6_reg;
        trunc_ln110_3_reg_1579_pp0_iter8_reg <= trunc_ln110_3_reg_1579_pp0_iter7_reg;
        trunc_ln110_4_reg_1584_pp0_iter2_reg <= trunc_ln110_4_reg_1584;
        trunc_ln110_4_reg_1584_pp0_iter3_reg <= trunc_ln110_4_reg_1584_pp0_iter2_reg;
        trunc_ln110_4_reg_1584_pp0_iter4_reg <= trunc_ln110_4_reg_1584_pp0_iter3_reg;
        trunc_ln110_4_reg_1584_pp0_iter5_reg <= trunc_ln110_4_reg_1584_pp0_iter4_reg;
        trunc_ln110_4_reg_1584_pp0_iter6_reg <= trunc_ln110_4_reg_1584_pp0_iter5_reg;
        trunc_ln110_4_reg_1584_pp0_iter7_reg <= trunc_ln110_4_reg_1584_pp0_iter6_reg;
        trunc_ln110_4_reg_1584_pp0_iter8_reg <= trunc_ln110_4_reg_1584_pp0_iter7_reg;
        trunc_ln110_4_reg_1584_pp0_iter9_reg <= trunc_ln110_4_reg_1584_pp0_iter8_reg;
        trunc_ln110_5_reg_1589_pp0_iter10_reg <= trunc_ln110_5_reg_1589_pp0_iter9_reg;
        trunc_ln110_5_reg_1589_pp0_iter2_reg <= trunc_ln110_5_reg_1589;
        trunc_ln110_5_reg_1589_pp0_iter3_reg <= trunc_ln110_5_reg_1589_pp0_iter2_reg;
        trunc_ln110_5_reg_1589_pp0_iter4_reg <= trunc_ln110_5_reg_1589_pp0_iter3_reg;
        trunc_ln110_5_reg_1589_pp0_iter5_reg <= trunc_ln110_5_reg_1589_pp0_iter4_reg;
        trunc_ln110_5_reg_1589_pp0_iter6_reg <= trunc_ln110_5_reg_1589_pp0_iter5_reg;
        trunc_ln110_5_reg_1589_pp0_iter7_reg <= trunc_ln110_5_reg_1589_pp0_iter6_reg;
        trunc_ln110_5_reg_1589_pp0_iter8_reg <= trunc_ln110_5_reg_1589_pp0_iter7_reg;
        trunc_ln110_5_reg_1589_pp0_iter9_reg <= trunc_ln110_5_reg_1589_pp0_iter8_reg;
        trunc_ln110_6_reg_1594_pp0_iter10_reg <= trunc_ln110_6_reg_1594_pp0_iter9_reg;
        trunc_ln110_6_reg_1594_pp0_iter11_reg <= trunc_ln110_6_reg_1594_pp0_iter10_reg;
        trunc_ln110_6_reg_1594_pp0_iter2_reg <= trunc_ln110_6_reg_1594;
        trunc_ln110_6_reg_1594_pp0_iter3_reg <= trunc_ln110_6_reg_1594_pp0_iter2_reg;
        trunc_ln110_6_reg_1594_pp0_iter4_reg <= trunc_ln110_6_reg_1594_pp0_iter3_reg;
        trunc_ln110_6_reg_1594_pp0_iter5_reg <= trunc_ln110_6_reg_1594_pp0_iter4_reg;
        trunc_ln110_6_reg_1594_pp0_iter6_reg <= trunc_ln110_6_reg_1594_pp0_iter5_reg;
        trunc_ln110_6_reg_1594_pp0_iter7_reg <= trunc_ln110_6_reg_1594_pp0_iter6_reg;
        trunc_ln110_6_reg_1594_pp0_iter8_reg <= trunc_ln110_6_reg_1594_pp0_iter7_reg;
        trunc_ln110_6_reg_1594_pp0_iter9_reg <= trunc_ln110_6_reg_1594_pp0_iter8_reg;
        trunc_ln110_7_reg_1599_pp0_iter10_reg <= trunc_ln110_7_reg_1599_pp0_iter9_reg;
        trunc_ln110_7_reg_1599_pp0_iter11_reg <= trunc_ln110_7_reg_1599_pp0_iter10_reg;
        trunc_ln110_7_reg_1599_pp0_iter12_reg <= trunc_ln110_7_reg_1599_pp0_iter11_reg;
        trunc_ln110_7_reg_1599_pp0_iter2_reg <= trunc_ln110_7_reg_1599;
        trunc_ln110_7_reg_1599_pp0_iter3_reg <= trunc_ln110_7_reg_1599_pp0_iter2_reg;
        trunc_ln110_7_reg_1599_pp0_iter4_reg <= trunc_ln110_7_reg_1599_pp0_iter3_reg;
        trunc_ln110_7_reg_1599_pp0_iter5_reg <= trunc_ln110_7_reg_1599_pp0_iter4_reg;
        trunc_ln110_7_reg_1599_pp0_iter6_reg <= trunc_ln110_7_reg_1599_pp0_iter5_reg;
        trunc_ln110_7_reg_1599_pp0_iter7_reg <= trunc_ln110_7_reg_1599_pp0_iter6_reg;
        trunc_ln110_7_reg_1599_pp0_iter8_reg <= trunc_ln110_7_reg_1599_pp0_iter7_reg;
        trunc_ln110_7_reg_1599_pp0_iter9_reg <= trunc_ln110_7_reg_1599_pp0_iter8_reg;
        trunc_ln110_8_reg_1604_pp0_iter10_reg <= trunc_ln110_8_reg_1604_pp0_iter9_reg;
        trunc_ln110_8_reg_1604_pp0_iter11_reg <= trunc_ln110_8_reg_1604_pp0_iter10_reg;
        trunc_ln110_8_reg_1604_pp0_iter12_reg <= trunc_ln110_8_reg_1604_pp0_iter11_reg;
        trunc_ln110_8_reg_1604_pp0_iter13_reg <= trunc_ln110_8_reg_1604_pp0_iter12_reg;
        trunc_ln110_8_reg_1604_pp0_iter2_reg <= trunc_ln110_8_reg_1604;
        trunc_ln110_8_reg_1604_pp0_iter3_reg <= trunc_ln110_8_reg_1604_pp0_iter2_reg;
        trunc_ln110_8_reg_1604_pp0_iter4_reg <= trunc_ln110_8_reg_1604_pp0_iter3_reg;
        trunc_ln110_8_reg_1604_pp0_iter5_reg <= trunc_ln110_8_reg_1604_pp0_iter4_reg;
        trunc_ln110_8_reg_1604_pp0_iter6_reg <= trunc_ln110_8_reg_1604_pp0_iter5_reg;
        trunc_ln110_8_reg_1604_pp0_iter7_reg <= trunc_ln110_8_reg_1604_pp0_iter6_reg;
        trunc_ln110_8_reg_1604_pp0_iter8_reg <= trunc_ln110_8_reg_1604_pp0_iter7_reg;
        trunc_ln110_8_reg_1604_pp0_iter9_reg <= trunc_ln110_8_reg_1604_pp0_iter8_reg;
        trunc_ln110_9_reg_1609_pp0_iter10_reg <= trunc_ln110_9_reg_1609_pp0_iter9_reg;
        trunc_ln110_9_reg_1609_pp0_iter11_reg <= trunc_ln110_9_reg_1609_pp0_iter10_reg;
        trunc_ln110_9_reg_1609_pp0_iter12_reg <= trunc_ln110_9_reg_1609_pp0_iter11_reg;
        trunc_ln110_9_reg_1609_pp0_iter13_reg <= trunc_ln110_9_reg_1609_pp0_iter12_reg;
        trunc_ln110_9_reg_1609_pp0_iter14_reg <= trunc_ln110_9_reg_1609_pp0_iter13_reg;
        trunc_ln110_9_reg_1609_pp0_iter2_reg <= trunc_ln110_9_reg_1609;
        trunc_ln110_9_reg_1609_pp0_iter3_reg <= trunc_ln110_9_reg_1609_pp0_iter2_reg;
        trunc_ln110_9_reg_1609_pp0_iter4_reg <= trunc_ln110_9_reg_1609_pp0_iter3_reg;
        trunc_ln110_9_reg_1609_pp0_iter5_reg <= trunc_ln110_9_reg_1609_pp0_iter4_reg;
        trunc_ln110_9_reg_1609_pp0_iter6_reg <= trunc_ln110_9_reg_1609_pp0_iter5_reg;
        trunc_ln110_9_reg_1609_pp0_iter7_reg <= trunc_ln110_9_reg_1609_pp0_iter6_reg;
        trunc_ln110_9_reg_1609_pp0_iter8_reg <= trunc_ln110_9_reg_1609_pp0_iter7_reg;
        trunc_ln110_9_reg_1609_pp0_iter9_reg <= trunc_ln110_9_reg_1609_pp0_iter8_reg;
        trunc_ln110_s_reg_1564_pp0_iter2_reg <= trunc_ln110_s_reg_1564;
        trunc_ln110_s_reg_1564_pp0_iter3_reg <= trunc_ln110_s_reg_1564_pp0_iter2_reg;
        trunc_ln110_s_reg_1564_pp0_iter4_reg <= trunc_ln110_s_reg_1564_pp0_iter3_reg;
        trunc_ln110_s_reg_1564_pp0_iter5_reg <= trunc_ln110_s_reg_1564_pp0_iter4_reg;
        trunc_ln1_reg_1624_pp0_iter10_reg <= trunc_ln1_reg_1624_pp0_iter9_reg;
        trunc_ln1_reg_1624_pp0_iter11_reg <= trunc_ln1_reg_1624_pp0_iter10_reg;
        trunc_ln1_reg_1624_pp0_iter12_reg <= trunc_ln1_reg_1624_pp0_iter11_reg;
        trunc_ln1_reg_1624_pp0_iter13_reg <= trunc_ln1_reg_1624_pp0_iter12_reg;
        trunc_ln1_reg_1624_pp0_iter14_reg <= trunc_ln1_reg_1624_pp0_iter13_reg;
        trunc_ln1_reg_1624_pp0_iter15_reg <= trunc_ln1_reg_1624_pp0_iter14_reg;
        trunc_ln1_reg_1624_pp0_iter16_reg <= trunc_ln1_reg_1624_pp0_iter15_reg;
        trunc_ln1_reg_1624_pp0_iter17_reg <= trunc_ln1_reg_1624_pp0_iter16_reg;
        trunc_ln1_reg_1624_pp0_iter2_reg <= trunc_ln1_reg_1624;
        trunc_ln1_reg_1624_pp0_iter3_reg <= trunc_ln1_reg_1624_pp0_iter2_reg;
        trunc_ln1_reg_1624_pp0_iter4_reg <= trunc_ln1_reg_1624_pp0_iter3_reg;
        trunc_ln1_reg_1624_pp0_iter5_reg <= trunc_ln1_reg_1624_pp0_iter4_reg;
        trunc_ln1_reg_1624_pp0_iter6_reg <= trunc_ln1_reg_1624_pp0_iter5_reg;
        trunc_ln1_reg_1624_pp0_iter7_reg <= trunc_ln1_reg_1624_pp0_iter6_reg;
        trunc_ln1_reg_1624_pp0_iter8_reg <= trunc_ln1_reg_1624_pp0_iter7_reg;
        trunc_ln1_reg_1624_pp0_iter9_reg <= trunc_ln1_reg_1624_pp0_iter8_reg;
        trunc_ln4_reg_1554_pp0_iter2_reg <= trunc_ln4_reg_1554;
        trunc_ln4_reg_1554_pp0_iter3_reg <= trunc_ln4_reg_1554_pp0_iter2_reg;
        trunc_ln_reg_1559_pp0_iter2_reg <= trunc_ln_reg_1559;
        trunc_ln_reg_1559_pp0_iter3_reg <= trunc_ln_reg_1559_pp0_iter2_reg;
        trunc_ln_reg_1559_pp0_iter4_reg <= trunc_ln_reg_1559_pp0_iter3_reg;
        w_idx_10_reg_1910 <= w_idx_10_fu_1180_p1;
        w_idx_11_reg_1938 <= w_idx_11_fu_1231_p1;
        w_idx_12_reg_1966 <= w_idx_12_fu_1282_p1;
        w_idx_13_reg_1994 <= w_idx_13_fu_1333_p1;
        w_idx_14_reg_2021 <= w_idx_14_fu_1384_p1;
        w_idx_1_reg_1658 <= w_idx_1_fu_721_p1;
        w_idx_2_reg_1686 <= w_idx_2_fu_772_p1;
        w_idx_3_reg_1714 <= w_idx_3_fu_823_p1;
        w_idx_4_reg_1742 <= w_idx_4_fu_874_p1;
        w_idx_5_reg_1770 <= w_idx_5_fu_925_p1;
        w_idx_6_reg_1798 <= w_idx_6_fu_976_p1;
        w_idx_7_reg_1826 <= w_idx_7_fu_1027_p1;
        w_idx_8_reg_1854 <= w_idx_8_fu_1078_p1;
        w_idx_9_reg_1882 <= w_idx_9_fu_1129_p1;
        w_idy_10_reg_1915 <= w_idy_10_fu_1184_p3;
        w_idy_11_reg_1943 <= w_idy_11_fu_1235_p3;
        w_idy_12_reg_1971 <= w_idy_12_fu_1286_p3;
        w_idy_13_reg_1999 <= w_idy_13_fu_1337_p3;
        w_idy_14_reg_2027 <= w_idy_14_fu_1388_p3;
        w_idy_1_reg_1663 <= w_idy_1_fu_725_p3;
        w_idy_2_reg_1691 <= w_idy_2_fu_776_p3;
        w_idy_3_reg_1719 <= w_idy_3_fu_827_p3;
        w_idy_4_reg_1747 <= w_idy_4_fu_878_p3;
        w_idy_5_reg_1775 <= w_idy_5_fu_929_p3;
        w_idy_6_reg_1803 <= w_idy_6_fu_980_p3;
        w_idy_7_reg_1831 <= w_idy_7_fu_1031_p3;
        w_idy_8_reg_1859 <= w_idy_8_fu_1082_p3;
        w_idy_9_reg_1887 <= w_idy_9_fu_1133_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        tmp_data_reg_1549 <= tmp_data_fu_485_p1;
        tmp_x_3_reg_1629 <= tmp_x_3_fu_661_p3;
        trunc_ln110_10_reg_1614 <= {{inStream_dout[439:416]}};
        trunc_ln110_11_reg_1619 <= {{inStream_dout[471:448]}};
        trunc_ln110_1_reg_1569 <= {{inStream_dout[151:128]}};
        trunc_ln110_2_reg_1574 <= {{inStream_dout[183:160]}};
        trunc_ln110_3_reg_1579 <= {{inStream_dout[215:192]}};
        trunc_ln110_4_reg_1584 <= {{inStream_dout[247:224]}};
        trunc_ln110_5_reg_1589 <= {{inStream_dout[279:256]}};
        trunc_ln110_6_reg_1594 <= {{inStream_dout[311:288]}};
        trunc_ln110_7_reg_1599 <= {{inStream_dout[343:320]}};
        trunc_ln110_8_reg_1604 <= {{inStream_dout[375:352]}};
        trunc_ln110_9_reg_1609 <= {{inStream_dout[407:384]}};
        trunc_ln110_s_reg_1564 <= {{inStream_dout[119:96]}};
        trunc_ln1_reg_1624 <= {{inStream_dout[503:480]}};
        trunc_ln4_reg_1554 <= {{inStream_dout[55:32]}};
        trunc_ln_reg_1559 <= {{inStream_dout[87:64]}};
        w_idx_reg_1635 <= w_idx_fu_669_p1;
        w_idy_reg_1640 <= w_idy_fu_673_p3;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln107_fu_468_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_idx_2 = 15'd0;
    end else begin
        ap_sig_allocacmp_idx_2 = idx_fu_126;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        inStream_blk_n = inStream_empty_n;
    end else begin
        inStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        inStream_read = 1'b1;
    end else begin
        inStream_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        outStream_blk_n = outStream_full_n;
    end else begin
        outStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        outStream_write = 1'b1;
    end else begin
        outStream_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce0 = 1'b1;
    end else begin
        watermark_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce1 = 1'b1;
    end else begin
        watermark_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce10 = 1'b1;
    end else begin
        watermark_ce10 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce11 = 1'b1;
    end else begin
        watermark_ce11 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce12 = 1'b1;
    end else begin
        watermark_ce12 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce13 = 1'b1;
    end else begin
        watermark_ce13 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce14 = 1'b1;
    end else begin
        watermark_ce14 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce15 = 1'b1;
    end else begin
        watermark_ce15 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce2 = 1'b1;
    end else begin
        watermark_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce3 = 1'b1;
    end else begin
        watermark_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce4 = 1'b1;
    end else begin
        watermark_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce5 = 1'b1;
    end else begin
        watermark_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce6 = 1'b1;
    end else begin
        watermark_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce7 = 1'b1;
    end else begin
        watermark_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce8 = 1'b1;
    end else begin
        watermark_ce8 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        watermark_ce9 = 1'b1;
    end else begin
        watermark_ce9 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        xStream_blk_n = xStream_empty_n;
    end else begin
        xStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        xStream_read = 1'b1;
    end else begin
        xStream_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        yStream_blk_n = yStream_empty_n;
    end else begin
        yStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        yStream_read = 1'b1;
    end else begin
        yStream_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)) | ((ap_enable_reg_pp0_iter19 == 1'b1) & (outStream_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((inStream_empty_n == 1'b0) | (yStream_empty_n == 1'b0) | (xStream_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)) | ((ap_enable_reg_pp0_iter19 == 1'b1) & (outStream_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((inStream_empty_n == 1'b0) | (yStream_empty_n == 1'b0) | (xStream_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)) | ((ap_enable_reg_pp0_iter19 == 1'b1) & (outStream_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((inStream_empty_n == 1'b0) | (yStream_empty_n == 1'b0) | (xStream_empty_n == 1'b0))));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state20_pp0_stage0_iter19 = (outStream_full_n == 1'b0);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((inStream_empty_n == 1'b0) | (yStream_empty_n == 1'b0) | (xStream_empty_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_859 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln107_fu_468_p2 = ((ap_sig_allocacmp_idx_2 == 15'd31568) ? 1'b1 : 1'b0);

assign icmp_ln119_10_fu_1156_p2 = ((tmp_x_31_fu_1151_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_11_fu_1207_p2 = ((tmp_x_34_fu_1202_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_12_fu_1258_p2 = ((tmp_x_37_fu_1253_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_13_fu_1309_p2 = ((tmp_x_40_fu_1304_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_14_fu_1360_p2 = ((tmp_x_43_fu_1355_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_15_fu_1411_p2 = ((tmp_x_46_fu_1406_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_1_fu_697_p2 = ((tmp_x_4_fu_692_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_2_fu_748_p2 = ((tmp_x_7_fu_743_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_3_fu_799_p2 = ((tmp_x_10_fu_794_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_4_fu_850_p2 = ((tmp_x_13_fu_845_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_5_fu_901_p2 = ((tmp_x_16_fu_896_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_6_fu_952_p2 = ((tmp_x_19_fu_947_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_7_fu_1003_p2 = ((tmp_x_22_fu_998_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_8_fu_1054_p2 = ((tmp_x_25_fu_1049_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_9_fu_1105_p2 = ((tmp_x_28_fu_1100_p2 > 32'd920) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_643_p2 = ((xStream_dout > 32'd920) ? 1'b1 : 1'b0);

assign idx_3_fu_474_p2 = (ap_sig_allocacmp_idx_2 + 15'd1);

assign or_ln174_i_fu_1498_p17 = {{{{{{{{{{{{{{{{tmp_29_i_reg_2064}, {zext_ln128_12_fu_1495_p1}}, {zext_ln128_11_fu_1492_p1}}, {zext_ln128_10_fu_1489_p1}}, {zext_ln128_9_fu_1486_p1}}, {zext_ln128_8_fu_1483_p1}}, {zext_ln128_7_fu_1480_p1}}, {zext_ln128_6_fu_1477_p1}}, {zext_ln128_5_fu_1474_p1}}, {zext_ln128_4_fu_1471_p1}}, {zext_ln128_3_fu_1468_p1}}, {zext_ln128_2_fu_1465_p1}}, {zext_ln128_1_fu_1462_p1}}, {zext_ln128_fu_1459_p1}}, {zext_ln105_1_fu_1456_p1}}, {zext_ln105_fu_1453_p1}};

assign outStream_din = or_ln174_i_fu_1498_p17;

assign select_ln119_31_fu_1435_p3 = ((icmp_ln119_15_fu_1411_p2[0:0] == 1'b1) ? tmp_y_31_fu_1417_p2 : w_idy_14_reg_2027);

assign select_ln119_fu_1422_p3 = ((icmp_ln119_15_fu_1411_p2[0:0] == 1'b1) ? 4'd9 : 4'd1);

assign tmp_10_fu_1191_p3 = {{w_idy_10_reg_1915}, {w_idx_10_reg_1910}};

assign tmp_11_fu_1242_p3 = {{w_idy_11_reg_1943}, {w_idx_11_reg_1938}};

assign tmp_12_fu_1293_p3 = {{w_idy_12_reg_1971}, {w_idx_12_reg_1966}};

assign tmp_13_fu_1344_p3 = {{w_idy_13_reg_1999}, {w_idx_13_reg_1994}};

assign tmp_14_fu_1395_p3 = {{w_idy_14_reg_2027}, {w_idx_14_reg_2021}};

assign tmp_15_fu_1442_p3 = {{select_ln119_31_reg_2049}, {tmp_x_reg_2044}};

assign tmp_1_fu_1089_p3 = {{w_idy_8_reg_1859}, {w_idx_8_reg_1854}};

assign tmp_2_fu_1140_p3 = {{w_idy_9_reg_1887}, {w_idx_9_reg_1882}};

assign tmp_3_fu_681_p3 = {{w_idy_reg_1640}, {w_idx_reg_1635}};

assign tmp_4_fu_732_p3 = {{w_idy_1_reg_1663}, {w_idx_1_reg_1658}};

assign tmp_5_fu_783_p3 = {{w_idy_2_reg_1691}, {w_idx_2_reg_1686}};

assign tmp_6_fu_834_p3 = {{w_idy_3_reg_1719}, {w_idx_3_reg_1714}};

assign tmp_7_fu_885_p3 = {{w_idy_4_reg_1747}, {w_idx_4_reg_1742}};

assign tmp_8_fu_936_p3 = {{w_idy_5_reg_1775}, {w_idx_5_reg_1770}};

assign tmp_9_fu_987_p3 = {{w_idy_6_reg_1803}, {w_idx_6_reg_1798}};

assign tmp_data_fu_485_p1 = inStream_dout[23:0];

assign tmp_s_fu_1038_p3 = {{w_idy_7_reg_1831}, {w_idx_7_reg_1826}};

assign tmp_x_10_fu_794_p2 = (tmp_x_9_reg_1680 + 32'd1);

assign tmp_x_11_fu_805_p2 = ($signed(tmp_x_9_reg_1680) + $signed(32'd4294966377));

assign tmp_x_12_fu_815_p3 = ((icmp_ln119_3_fu_799_p2[0:0] == 1'b1) ? tmp_x_11_fu_805_p2 : tmp_x_10_fu_794_p2);

assign tmp_x_13_fu_845_p2 = (tmp_x_12_reg_1708 + 32'd1);

assign tmp_x_14_fu_856_p2 = ($signed(tmp_x_12_reg_1708) + $signed(32'd4294966377));

assign tmp_x_15_fu_866_p3 = ((icmp_ln119_4_fu_850_p2[0:0] == 1'b1) ? tmp_x_14_fu_856_p2 : tmp_x_13_fu_845_p2);

assign tmp_x_16_fu_896_p2 = (tmp_x_15_reg_1736 + 32'd1);

assign tmp_x_17_fu_907_p2 = ($signed(tmp_x_15_reg_1736) + $signed(32'd4294966377));

assign tmp_x_18_fu_917_p3 = ((icmp_ln119_5_fu_901_p2[0:0] == 1'b1) ? tmp_x_17_fu_907_p2 : tmp_x_16_fu_896_p2);

assign tmp_x_19_fu_947_p2 = (tmp_x_18_reg_1764 + 32'd1);

assign tmp_x_20_fu_958_p2 = ($signed(tmp_x_18_reg_1764) + $signed(32'd4294966377));

assign tmp_x_21_fu_968_p3 = ((icmp_ln119_6_fu_952_p2[0:0] == 1'b1) ? tmp_x_20_fu_958_p2 : tmp_x_19_fu_947_p2);

assign tmp_x_22_fu_998_p2 = (tmp_x_21_reg_1792 + 32'd1);

assign tmp_x_23_fu_1009_p2 = ($signed(tmp_x_21_reg_1792) + $signed(32'd4294966377));

assign tmp_x_24_fu_1019_p3 = ((icmp_ln119_7_fu_1003_p2[0:0] == 1'b1) ? tmp_x_23_fu_1009_p2 : tmp_x_22_fu_998_p2);

assign tmp_x_25_fu_1049_p2 = (tmp_x_24_reg_1820 + 32'd1);

assign tmp_x_26_fu_1060_p2 = ($signed(tmp_x_24_reg_1820) + $signed(32'd4294966377));

assign tmp_x_27_fu_1070_p3 = ((icmp_ln119_8_fu_1054_p2[0:0] == 1'b1) ? tmp_x_26_fu_1060_p2 : tmp_x_25_fu_1049_p2);

assign tmp_x_28_fu_1100_p2 = (tmp_x_27_reg_1848 + 32'd1);

assign tmp_x_29_fu_1111_p2 = ($signed(tmp_x_27_reg_1848) + $signed(32'd4294966377));

assign tmp_x_2_fu_649_p2 = ($signed(xStream_dout) + $signed(32'd4294966376));

assign tmp_x_30_fu_1121_p3 = ((icmp_ln119_9_fu_1105_p2[0:0] == 1'b1) ? tmp_x_29_fu_1111_p2 : tmp_x_28_fu_1100_p2);

assign tmp_x_31_fu_1151_p2 = (tmp_x_30_reg_1876 + 32'd1);

assign tmp_x_32_fu_1162_p2 = ($signed(tmp_x_30_reg_1876) + $signed(32'd4294966377));

assign tmp_x_33_fu_1172_p3 = ((icmp_ln119_10_fu_1156_p2[0:0] == 1'b1) ? tmp_x_32_fu_1162_p2 : tmp_x_31_fu_1151_p2);

assign tmp_x_34_fu_1202_p2 = (tmp_x_33_reg_1904 + 32'd1);

assign tmp_x_35_fu_1213_p2 = ($signed(tmp_x_33_reg_1904) + $signed(32'd4294966377));

assign tmp_x_36_fu_1223_p3 = ((icmp_ln119_11_fu_1207_p2[0:0] == 1'b1) ? tmp_x_35_fu_1213_p2 : tmp_x_34_fu_1202_p2);

assign tmp_x_37_fu_1253_p2 = (tmp_x_36_reg_1932 + 32'd1);

assign tmp_x_38_fu_1264_p2 = ($signed(tmp_x_36_reg_1932) + $signed(32'd4294966377));

assign tmp_x_39_fu_1274_p3 = ((icmp_ln119_12_fu_1258_p2[0:0] == 1'b1) ? tmp_x_38_fu_1264_p2 : tmp_x_37_fu_1253_p2);

assign tmp_x_3_fu_661_p3 = ((icmp_ln119_fu_643_p2[0:0] == 1'b1) ? tmp_x_2_fu_649_p2 : xStream_dout);

assign tmp_x_40_fu_1304_p2 = (tmp_x_39_reg_1960 + 32'd1);

assign tmp_x_41_fu_1315_p2 = ($signed(tmp_x_39_reg_1960) + $signed(32'd4294966377));

assign tmp_x_42_fu_1325_p3 = ((icmp_ln119_13_fu_1309_p2[0:0] == 1'b1) ? tmp_x_41_fu_1315_p2 : tmp_x_40_fu_1304_p2);

assign tmp_x_43_fu_1355_p2 = (tmp_x_42_reg_1988 + 32'd1);

assign tmp_x_44_fu_1366_p2 = ($signed(tmp_x_42_reg_1988) + $signed(32'd4294966377));

assign tmp_x_45_fu_1376_p3 = ((icmp_ln119_14_fu_1360_p2[0:0] == 1'b1) ? tmp_x_44_fu_1366_p2 : tmp_x_43_fu_1355_p2);

assign tmp_x_46_fu_1406_p2 = (tmp_x_45_reg_2016 + 32'd1);

assign tmp_x_4_fu_692_p2 = (tmp_x_3_reg_1629 + 32'd1);

assign tmp_x_5_fu_703_p2 = ($signed(tmp_x_3_reg_1629) + $signed(32'd4294966377));

assign tmp_x_6_fu_713_p3 = ((icmp_ln119_1_fu_697_p2[0:0] == 1'b1) ? tmp_x_5_fu_703_p2 : tmp_x_4_fu_692_p2);

assign tmp_x_7_fu_743_p2 = (tmp_x_6_reg_1652 + 32'd1);

assign tmp_x_8_fu_754_p2 = ($signed(tmp_x_6_reg_1652) + $signed(32'd4294966377));

assign tmp_x_9_fu_764_p3 = ((icmp_ln119_2_fu_748_p2[0:0] == 1'b1) ? tmp_x_8_fu_754_p2 : tmp_x_7_fu_743_p2);

assign tmp_x_fu_1430_p2 = (w_idx_14_reg_2021 + select_ln119_fu_1422_p3);

assign tmp_y_11_fu_912_p2 = (w_idy_4_reg_1747 + 4'd1);

assign tmp_y_13_fu_963_p2 = (w_idy_5_reg_1775 + 4'd1);

assign tmp_y_15_fu_1014_p2 = (w_idy_6_reg_1803 + 4'd1);

assign tmp_y_17_fu_1065_p2 = (w_idy_7_reg_1831 + 4'd1);

assign tmp_y_19_fu_1116_p2 = (w_idy_8_reg_1859 + 4'd1);

assign tmp_y_1_fu_655_p2 = (trunc_ln155_fu_639_p1 + 4'd1);

assign tmp_y_21_fu_1167_p2 = (w_idy_9_reg_1887 + 4'd1);

assign tmp_y_23_fu_1218_p2 = (w_idy_10_reg_1915 + 4'd1);

assign tmp_y_25_fu_1269_p2 = (w_idy_11_reg_1943 + 4'd1);

assign tmp_y_27_fu_1320_p2 = (w_idy_12_reg_1971 + 4'd1);

assign tmp_y_29_fu_1371_p2 = (w_idy_13_reg_1999 + 4'd1);

assign tmp_y_31_fu_1417_p2 = (w_idy_14_reg_2027 + 4'd1);

assign tmp_y_3_fu_708_p2 = (w_idy_reg_1640 + 4'd1);

assign tmp_y_5_fu_759_p2 = (w_idy_1_reg_1663 + 4'd1);

assign tmp_y_7_fu_810_p2 = (w_idy_2_reg_1691 + 4'd1);

assign tmp_y_9_fu_861_p2 = (w_idy_3_reg_1719 + 4'd1);

assign trunc_ln155_fu_639_p1 = yStream_dout[3:0];

assign w_idx_10_fu_1180_p1 = tmp_x_33_fu_1172_p3[3:0];

assign w_idx_11_fu_1231_p1 = tmp_x_36_fu_1223_p3[3:0];

assign w_idx_12_fu_1282_p1 = tmp_x_39_fu_1274_p3[3:0];

assign w_idx_13_fu_1333_p1 = tmp_x_42_fu_1325_p3[3:0];

assign w_idx_14_fu_1384_p1 = tmp_x_45_fu_1376_p3[3:0];

assign w_idx_1_fu_721_p1 = tmp_x_6_fu_713_p3[3:0];

assign w_idx_2_fu_772_p1 = tmp_x_9_fu_764_p3[3:0];

assign w_idx_3_fu_823_p1 = tmp_x_12_fu_815_p3[3:0];

assign w_idx_4_fu_874_p1 = tmp_x_15_fu_866_p3[3:0];

assign w_idx_5_fu_925_p1 = tmp_x_18_fu_917_p3[3:0];

assign w_idx_6_fu_976_p1 = tmp_x_21_fu_968_p3[3:0];

assign w_idx_7_fu_1027_p1 = tmp_x_24_fu_1019_p3[3:0];

assign w_idx_8_fu_1078_p1 = tmp_x_27_fu_1070_p3[3:0];

assign w_idx_9_fu_1129_p1 = tmp_x_30_fu_1121_p3[3:0];

assign w_idx_fu_669_p1 = tmp_x_3_fu_661_p3[3:0];

assign w_idy_10_fu_1184_p3 = ((icmp_ln119_10_fu_1156_p2[0:0] == 1'b1) ? tmp_y_21_fu_1167_p2 : w_idy_9_reg_1887);

assign w_idy_11_fu_1235_p3 = ((icmp_ln119_11_fu_1207_p2[0:0] == 1'b1) ? tmp_y_23_fu_1218_p2 : w_idy_10_reg_1915);

assign w_idy_12_fu_1286_p3 = ((icmp_ln119_12_fu_1258_p2[0:0] == 1'b1) ? tmp_y_25_fu_1269_p2 : w_idy_11_reg_1943);

assign w_idy_13_fu_1337_p3 = ((icmp_ln119_13_fu_1309_p2[0:0] == 1'b1) ? tmp_y_27_fu_1320_p2 : w_idy_12_reg_1971);

assign w_idy_14_fu_1388_p3 = ((icmp_ln119_14_fu_1360_p2[0:0] == 1'b1) ? tmp_y_29_fu_1371_p2 : w_idy_13_reg_1999);

assign w_idy_1_fu_725_p3 = ((icmp_ln119_1_fu_697_p2[0:0] == 1'b1) ? tmp_y_3_fu_708_p2 : w_idy_reg_1640);

assign w_idy_2_fu_776_p3 = ((icmp_ln119_2_fu_748_p2[0:0] == 1'b1) ? tmp_y_5_fu_759_p2 : w_idy_1_reg_1663);

assign w_idy_3_fu_827_p3 = ((icmp_ln119_3_fu_799_p2[0:0] == 1'b1) ? tmp_y_7_fu_810_p2 : w_idy_2_reg_1691);

assign w_idy_4_fu_878_p3 = ((icmp_ln119_4_fu_850_p2[0:0] == 1'b1) ? tmp_y_9_fu_861_p2 : w_idy_3_reg_1719);

assign w_idy_5_fu_929_p3 = ((icmp_ln119_5_fu_901_p2[0:0] == 1'b1) ? tmp_y_11_fu_912_p2 : w_idy_4_reg_1747);

assign w_idy_6_fu_980_p3 = ((icmp_ln119_6_fu_952_p2[0:0] == 1'b1) ? tmp_y_13_fu_963_p2 : w_idy_5_reg_1775);

assign w_idy_7_fu_1031_p3 = ((icmp_ln119_7_fu_1003_p2[0:0] == 1'b1) ? tmp_y_15_fu_1014_p2 : w_idy_6_reg_1803);

assign w_idy_8_fu_1082_p3 = ((icmp_ln119_8_fu_1054_p2[0:0] == 1'b1) ? tmp_y_17_fu_1065_p2 : w_idy_7_reg_1831);

assign w_idy_9_fu_1133_p3 = ((icmp_ln119_9_fu_1105_p2[0:0] == 1'b1) ? tmp_y_19_fu_1116_p2 : w_idy_8_reg_1859);

assign w_idy_fu_673_p3 = ((icmp_ln119_fu_643_p2[0:0] == 1'b1) ? tmp_y_1_fu_655_p2 : trunc_ln155_fu_639_p1);

assign watermark_address0 = zext_ln126_15_fu_1448_p1;

assign watermark_address1 = zext_ln126_14_fu_1401_p1;

assign watermark_address10 = zext_ln126_5_fu_942_p1;

assign watermark_address11 = zext_ln126_4_fu_891_p1;

assign watermark_address12 = zext_ln126_3_fu_840_p1;

assign watermark_address13 = zext_ln126_2_fu_789_p1;

assign watermark_address14 = zext_ln126_1_fu_738_p1;

assign watermark_address15 = zext_ln126_fu_687_p1;

assign watermark_address2 = zext_ln126_13_fu_1350_p1;

assign watermark_address3 = zext_ln126_12_fu_1299_p1;

assign watermark_address4 = zext_ln126_11_fu_1248_p1;

assign watermark_address5 = zext_ln126_10_fu_1197_p1;

assign watermark_address6 = zext_ln126_9_fu_1146_p1;

assign watermark_address7 = zext_ln126_8_fu_1095_p1;

assign watermark_address8 = zext_ln126_7_fu_1044_p1;

assign watermark_address9 = zext_ln126_6_fu_993_p1;

assign zext_ln105_1_fu_1456_p1 = tmp_data_2_reg_1698_pp0_iter18_reg;

assign zext_ln105_fu_1453_p1 = tmp_data_1_reg_1670_pp0_iter18_reg;

assign zext_ln126_10_fu_1197_p1 = tmp_10_fu_1191_p3;

assign zext_ln126_11_fu_1248_p1 = tmp_11_fu_1242_p3;

assign zext_ln126_12_fu_1299_p1 = tmp_12_fu_1293_p3;

assign zext_ln126_13_fu_1350_p1 = tmp_13_fu_1344_p3;

assign zext_ln126_14_fu_1401_p1 = tmp_14_fu_1395_p3;

assign zext_ln126_15_fu_1448_p1 = tmp_15_fu_1442_p3;

assign zext_ln126_1_fu_738_p1 = tmp_4_fu_732_p3;

assign zext_ln126_2_fu_789_p1 = tmp_5_fu_783_p3;

assign zext_ln126_3_fu_840_p1 = tmp_6_fu_834_p3;

assign zext_ln126_4_fu_891_p1 = tmp_7_fu_885_p3;

assign zext_ln126_5_fu_942_p1 = tmp_8_fu_936_p3;

assign zext_ln126_6_fu_993_p1 = tmp_9_fu_987_p3;

assign zext_ln126_7_fu_1044_p1 = tmp_s_fu_1038_p3;

assign zext_ln126_8_fu_1095_p1 = tmp_1_fu_1089_p3;

assign zext_ln126_9_fu_1146_p1 = tmp_2_fu_1140_p3;

assign zext_ln126_fu_687_p1 = tmp_3_fu_681_p3;

assign zext_ln128_10_fu_1489_p1 = tmp_26_i_reg_2006_pp0_iter18_reg;

assign zext_ln128_11_fu_1492_p1 = tmp_27_i_reg_2034_pp0_iter18_reg;

assign zext_ln128_12_fu_1495_p1 = tmp_28_i_reg_2054_pp0_iter18_reg;

assign zext_ln128_1_fu_1462_p1 = tmp_17_i_reg_1754_pp0_iter18_reg;

assign zext_ln128_2_fu_1465_p1 = tmp_18_i_reg_1782_pp0_iter18_reg;

assign zext_ln128_3_fu_1468_p1 = tmp_19_i_reg_1810_pp0_iter18_reg;

assign zext_ln128_4_fu_1471_p1 = tmp_20_i_reg_1838_pp0_iter18_reg;

assign zext_ln128_5_fu_1474_p1 = tmp_21_i_reg_1866_pp0_iter18_reg;

assign zext_ln128_6_fu_1477_p1 = tmp_22_i_reg_1894_pp0_iter18_reg;

assign zext_ln128_7_fu_1480_p1 = tmp_23_i_reg_1922_pp0_iter18_reg;

assign zext_ln128_8_fu_1483_p1 = tmp_24_i_reg_1950_pp0_iter18_reg;

assign zext_ln128_9_fu_1486_p1 = tmp_25_i_reg_1978_pp0_iter18_reg;

assign zext_ln128_fu_1459_p1 = tmp_16_i_reg_1726_pp0_iter18_reg;

endmodule //apply_watermark_compute_watermark
