// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1.2 (64-bit)
// Version: 2022.1.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module apply_watermark_saturatedAdd (
        ap_ready,
        x,
        y,
        ap_return
);


output   ap_ready;
input  [23:0] x;
input  [16:0] y;
output  [23:0] ap_return;

wire   [7:0] redX_fu_52_p1;
wire   [7:0] redY_fu_48_p1;
wire   [7:0] greenX_fu_64_p4;
wire   [7:0] greenY_fu_78_p4;
wire   [7:0] blueX_fu_92_p4;
wire   [0:0] tmp_fu_106_p3;
wire   [8:0] zext_ln181_fu_60_p1;
wire   [8:0] zext_ln180_fu_56_p1;
wire   [8:0] redOutput_fu_122_p2;
wire   [0:0] tmp_1_fu_134_p3;
wire   [7:0] add_ln195_1_fu_128_p2;
wire   [8:0] zext_ln186_fu_88_p1;
wire   [8:0] zext_ln185_fu_74_p1;
wire   [8:0] greenOutput_fu_150_p2;
wire   [0:0] tmp_2_fu_162_p3;
wire   [7:0] add_ln202_1_fu_156_p2;
wire   [8:0] select_ln195_fu_114_p3;
wire   [8:0] zext_ln190_fu_102_p1;
wire   [7:0] select_ln209_fu_178_p3;
wire   [8:0] blueOutput_fu_186_p2;
wire   [0:0] tmp_3_fu_198_p3;
wire   [7:0] add_ln209_1_fu_192_p2;
wire   [7:0] blueOutput_1_fu_206_p3;
wire   [7:0] greenOutput_1_fu_170_p3;
wire   [7:0] redOutput_2_fu_142_p3;

assign add_ln195_1_fu_128_p2 = (redY_fu_48_p1 + redX_fu_52_p1);

assign add_ln202_1_fu_156_p2 = (greenY_fu_78_p4 + greenX_fu_64_p4);

assign add_ln209_1_fu_192_p2 = (select_ln209_fu_178_p3 + blueX_fu_92_p4);

assign ap_ready = 1'b1;

assign ap_return = {{{blueOutput_1_fu_206_p3}, {greenOutput_1_fu_170_p3}}, {redOutput_2_fu_142_p3}};

assign blueOutput_1_fu_206_p3 = ((tmp_3_fu_198_p3[0:0] == 1'b1) ? 8'd255 : add_ln209_1_fu_192_p2);

assign blueOutput_fu_186_p2 = (select_ln195_fu_114_p3 + zext_ln190_fu_102_p1);

assign blueX_fu_92_p4 = {{x[23:16]}};

assign greenOutput_1_fu_170_p3 = ((tmp_2_fu_162_p3[0:0] == 1'b1) ? 8'd255 : add_ln202_1_fu_156_p2);

assign greenOutput_fu_150_p2 = (zext_ln186_fu_88_p1 + zext_ln185_fu_74_p1);

assign greenX_fu_64_p4 = {{x[15:8]}};

assign greenY_fu_78_p4 = {{y[15:8]}};

assign redOutput_2_fu_142_p3 = ((tmp_1_fu_134_p3[0:0] == 1'b1) ? 8'd255 : add_ln195_1_fu_128_p2);

assign redOutput_fu_122_p2 = (zext_ln181_fu_60_p1 + zext_ln180_fu_56_p1);

assign redX_fu_52_p1 = x[7:0];

assign redY_fu_48_p1 = y[7:0];

assign select_ln195_fu_114_p3 = ((tmp_fu_106_p3[0:0] == 1'b1) ? 9'd15 : 9'd0);

assign select_ln209_fu_178_p3 = ((tmp_fu_106_p3[0:0] == 1'b1) ? 8'd15 : 8'd0);

assign tmp_1_fu_134_p3 = redOutput_fu_122_p2[32'd8];

assign tmp_2_fu_162_p3 = greenOutput_fu_150_p2[32'd8];

assign tmp_3_fu_198_p3 = blueOutput_fu_186_p2[32'd8];

assign tmp_fu_106_p3 = y[32'd16];

assign zext_ln180_fu_56_p1 = redX_fu_52_p1;

assign zext_ln181_fu_60_p1 = redY_fu_48_p1;

assign zext_ln185_fu_74_p1 = greenX_fu_64_p4;

assign zext_ln186_fu_88_p1 = greenY_fu_78_p4;

assign zext_ln190_fu_102_p1 = blueX_fu_92_p4;

endmodule //apply_watermark_saturatedAdd
